package consumergroupheartbeat

import (
	"bytes"
	"errors"
	"io"

	"github.com/google/uuid"
	"github.com/scholzj/go-kafka-protocol/protocol"
)

const (
	ConsumerGroupHeartbeatRequestApiKey        = 68
	ConsumerGroupHeartbeatRequestHeaderVersion = 1
)

// ConsumerGroupHeartbeatRequest represents a request message.
type ConsumerGroupHeartbeatRequest struct {
	// The group identifier.
	GroupId string `json:"groupid" versions:"0-999"`
	// The member id generated by the consumer. The member id must be kept during the entire lifetime of the consumer process.
	MemberId string `json:"memberid" versions:"0-999"`
	// The current member epoch; 0 to join the group; -1 to leave the group; -2 to indicate that the static member will rejoin.
	MemberEpoch int32 `json:"memberepoch" versions:"0-999"`
	// null if not provided or if it didn't change since the last heartbeat; the instance Id otherwise.
	InstanceId *string `json:"instanceid" versions:"0-999"`
	// null if not provided or if it didn't change since the last heartbeat; the rack ID of consumer otherwise.
	RackId *string `json:"rackid" versions:"0-999"`
	// -1 if it didn't change since the last heartbeat; the maximum time in milliseconds that the coordinator will wait on the member to revoke its partitions otherwise.
	RebalanceTimeoutMs int32 `json:"rebalancetimeoutms" versions:"0-999"`
	// null if it didn't change since the last heartbeat; the subscribed topic names otherwise.
	SubscribedTopicNames []string `json:"subscribedtopicnames" versions:"0-999"`
	// null if it didn't change since the last heartbeat; the subscribed topic regex otherwise.
	SubscribedTopicRegex *string `json:"subscribedtopicregex" versions:"1-999"`
	// null if not used or if it didn't change since the last heartbeat; the server side assignor to use otherwise.
	ServerAssignor *string `json:"serverassignor" versions:"0-999"`
	// null if it didn't change since the last heartbeat; the partitions owned by the member.
	TopicPartitions []ConsumerGroupHeartbeatRequestTopicPartitions `json:"topicpartitions" versions:"0-999"`
}

// Encode encodes a ConsumerGroupHeartbeatRequest to a byte slice for the given version.
func (m *ConsumerGroupHeartbeatRequest) Encode(version int16) ([]byte, error) {
	var buf bytes.Buffer
	if err := m.Write(&buf, version); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Decode decodes a ConsumerGroupHeartbeatRequest from a byte slice for the given version.
func (m *ConsumerGroupHeartbeatRequest) Decode(data []byte, version int16) error {
	r := bytes.NewReader(data)
	return m.Read(r, version)
}

// Write writes a ConsumerGroupHeartbeatRequest to an io.Writer for the given version.
func (m *ConsumerGroupHeartbeatRequest) Write(w io.Writer, version int16) error {
	if version < 0 || version > 1 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// GroupId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactString(w, m.GroupId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteString(w, m.GroupId); err != nil {
				return err
			}
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactString(w, m.MemberId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteString(w, m.MemberId); err != nil {
				return err
			}
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.MemberEpoch); err != nil {
			return err
		}
	}
	// InstanceId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.InstanceId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.InstanceId); err != nil {
				return err
			}
		}
	}
	// RackId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.RackId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.RackId); err != nil {
				return err
			}
		}
	}
	// RebalanceTimeoutMs
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.RebalanceTimeoutMs); err != nil {
			return err
		}
	}
	// SubscribedTopicNames
	if version >= 0 && version <= 999 {
		if m.SubscribedTopicNames == nil {
			if isFlexible {
				if err := protocol.WriteVaruint32(w, 0); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, -1); err != nil {
					return err
				}
			}
		} else {
			if isFlexible {
				if err := protocol.WriteCompactStringArray(w, m.SubscribedTopicNames); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteStringArray(w, m.SubscribedTopicNames); err != nil {
					return err
				}
			}
		}
	}
	// SubscribedTopicRegex
	if version >= 1 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.SubscribedTopicRegex); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.SubscribedTopicRegex); err != nil {
				return err
			}
		}
	}
	// ServerAssignor
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.ServerAssignor); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.ServerAssignor); err != nil {
				return err
			}
		}
	}
	// TopicPartitions
	if version >= 0 && version <= 999 {
		// Encode array using ArrayEncoder
		encoder := func(item interface{}) ([]byte, error) {
			if item == nil {
				return nil, nil
			}
			structItem, ok := item.(ConsumerGroupHeartbeatRequestTopicPartitions)
			if !ok {
				return nil, errors.New("invalid type for array element")
			}
			var elemBuf bytes.Buffer
			// Temporarily use elemBuf as writer
			elemW := &elemBuf
			// TopicId
			if version >= 0 && version <= 999 {
				if err := protocol.WriteUUID(elemW, structItem.TopicId); err != nil {
					return nil, err
				}
			}
			// Partitions
			if version >= 0 && version <= 999 {
				if isFlexible {
					if err := protocol.WriteCompactInt32Array(elemW, structItem.Partitions); err != nil {
						return nil, err
					}
				} else {
					if err := protocol.WriteInt32Array(elemW, structItem.Partitions); err != nil {
						return nil, err
					}
				}
			}
			// Write tagged fields if flexible
			if isFlexible {
				if err := structItem.writeTaggedFields(elemW, version); err != nil {
					return nil, err
				}
			}
			return elemBuf.Bytes(), nil
		}
		items := make([]interface{}, len(m.TopicPartitions))
		for i := range m.TopicPartitions {
			items[i] = m.TopicPartitions[i]
		}
		if m.TopicPartitions == nil {
			if isFlexible {
				if err := protocol.WriteVaruint32(w, 0); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, -1); err != nil {
					return err
				}
			}
		} else {
			if isFlexible {
				if err := protocol.WriteCompactArray(w, items, encoder); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteArray(w, items, encoder); err != nil {
					return err
				}
			}
		}
	}
	// Write tagged fields if flexible
	if isFlexible {
		if err := m.writeTaggedFields(w, version); err != nil {
			return err
		}
	}
	return nil
}

// Read reads a ConsumerGroupHeartbeatRequest from an io.Reader for the given version.
func (m *ConsumerGroupHeartbeatRequest) Read(r io.Reader, version int16) error {
	if version < 0 || version > 1 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// GroupId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactString(r)
			if err != nil {
				return err
			}
			m.GroupId = val
		} else {
			val, err := protocol.ReadString(r)
			if err != nil {
				return err
			}
			m.GroupId = val
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		} else {
			val, err := protocol.ReadString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.MemberEpoch = val
	}
	// InstanceId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.InstanceId = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.InstanceId = val
		}
	}
	// RackId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.RackId = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.RackId = val
		}
	}
	// RebalanceTimeoutMs
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.RebalanceTimeoutMs = val
	}
	// SubscribedTopicNames
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactStringArray(r)
			if err != nil {
				return err
			}
			m.SubscribedTopicNames = val
		} else {
			val, err := protocol.ReadStringArray(r)
			if err != nil {
				return err
			}
			m.SubscribedTopicNames = val
		}
	}
	// SubscribedTopicRegex
	if version >= 1 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.SubscribedTopicRegex = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.SubscribedTopicRegex = val
		}
	}
	// ServerAssignor
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.ServerAssignor = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.ServerAssignor = val
		}
	}
	// TopicPartitions
	if version >= 0 && version <= 999 {
		// Decode array using ArrayDecoder
		decoder := func(data []byte) (interface{}, int, error) {
			var elem ConsumerGroupHeartbeatRequestTopicPartitions
			elemR := bytes.NewReader(data)
			// TopicId
			if version >= 0 && version <= 999 {
				val, err := protocol.ReadUUID(elemR)
				if err != nil {
					return nil, 0, err
				}
				elem.TopicId = val
			}
			// Partitions
			if version >= 0 && version <= 999 {
				if isFlexible {
					val, err := protocol.ReadCompactInt32Array(elemR)
					if err != nil {
						return nil, 0, err
					}
					elem.Partitions = val
				} else {
					val, err := protocol.ReadInt32Array(elemR)
					if err != nil {
						return nil, 0, err
					}
					elem.Partitions = val
				}
			}
			// Read tagged fields if flexible
			if isFlexible {
				if err := elem.readTaggedFields(elemR, version); err != nil {
					return nil, 0, err
				}
			}
			consumed := len(data) - elemR.Len()
			return elem, consumed, nil
		}
		if isFlexible {
			lengthUint, err := protocol.ReadVaruint32(r)
			if err != nil {
				return err
			}
			if lengthUint == 0 {
				m.TopicPartitions = nil
				return nil
			}
			if lengthUint < 1 {
				return errors.New("invalid compact array length")
			}
			length := int32(lengthUint - 1)
			// Collect all array elements into a buffer
			var arrayBuf bytes.Buffer
			for i := int32(0); i < length; i++ {
				// Read element into struct and encode to buffer
				var elemBuf bytes.Buffer
				elemW := &elemBuf
				var tempElem ConsumerGroupHeartbeatRequestTopicPartitions
				// TopicId
				if version >= 0 && version <= 999 {
					val, err := protocol.ReadUUID(r)
					if err != nil {
						return err
					}
					tempElem.TopicId = val
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						val, err := protocol.ReadCompactInt32Array(r)
						if err != nil {
							return err
						}
						tempElem.Partitions = val
					} else {
						val, err := protocol.ReadInt32Array(r)
						if err != nil {
							return err
						}
						tempElem.Partitions = val
					}
				}
				// TopicId
				if version >= 0 && version <= 999 {
					if err := protocol.WriteUUID(elemW, tempElem.TopicId); err != nil {
						return err
					}
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						if err := protocol.WriteCompactInt32Array(elemW, tempElem.Partitions); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteInt32Array(elemW, tempElem.Partitions); err != nil {
							return err
						}
					}
				}
				// Append to array buffer
				arrayBuf.Write(elemBuf.Bytes())
			}
			// Prepend length and decode using DecodeCompactArray
			lengthBytes := protocol.EncodeVaruint32(lengthUint)
			fullData := append(lengthBytes, arrayBuf.Bytes()...)
			decoded, _, err := protocol.DecodeCompactArray(fullData, decoder)
			if err != nil {
				return err
			}
			// Convert []interface{} to typed slice
			m.TopicPartitions = make([]ConsumerGroupHeartbeatRequestTopicPartitions, len(decoded))
			for i, item := range decoded {
				m.TopicPartitions[i] = item.(ConsumerGroupHeartbeatRequestTopicPartitions)
			}
		} else {
			length, err := protocol.ReadInt32(r)
			if err != nil {
				return err
			}
			if length == -1 {
				m.TopicPartitions = nil
				return nil
			}
			// Collect all array elements into a buffer
			var arrayBuf bytes.Buffer
			for i := int32(0); i < length; i++ {
				// Read element into struct and encode to buffer
				var elemBuf bytes.Buffer
				elemW := &elemBuf
				var tempElem ConsumerGroupHeartbeatRequestTopicPartitions
				// TopicId
				if version >= 0 && version <= 999 {
					val, err := protocol.ReadUUID(r)
					if err != nil {
						return err
					}
					tempElem.TopicId = val
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						val, err := protocol.ReadCompactInt32Array(r)
						if err != nil {
							return err
						}
						tempElem.Partitions = val
					} else {
						val, err := protocol.ReadInt32Array(r)
						if err != nil {
							return err
						}
						tempElem.Partitions = val
					}
				}
				// TopicId
				if version >= 0 && version <= 999 {
					if err := protocol.WriteUUID(elemW, tempElem.TopicId); err != nil {
						return err
					}
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						if err := protocol.WriteCompactInt32Array(elemW, tempElem.Partitions); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteInt32Array(elemW, tempElem.Partitions); err != nil {
							return err
						}
					}
				}
				// Append to array buffer
				arrayBuf.Write(elemBuf.Bytes())
			}
			// Prepend length and decode using DecodeArray
			lengthBytes := protocol.EncodeInt32(length)
			fullData := append(lengthBytes, arrayBuf.Bytes()...)
			decoded, _, err := protocol.DecodeArray(fullData, decoder)
			if err != nil {
				return err
			}
			// Convert []interface{} to typed slice
			m.TopicPartitions = make([]ConsumerGroupHeartbeatRequestTopicPartitions, len(decoded))
			for i, item := range decoded {
				m.TopicPartitions[i] = item.(ConsumerGroupHeartbeatRequestTopicPartitions)
			}
		}
	}
	// Read tagged fields if flexible
	if isFlexible {
		if err := m.readTaggedFields(r, version); err != nil {
			return err
		}
	}
	return nil
}

// ConsumerGroupHeartbeatRequestTopicPartitions represents null if it didn't change since the last heartbeat; the partitions owned by the member..
type ConsumerGroupHeartbeatRequestTopicPartitions struct {
	// The topic ID.
	TopicId uuid.UUID `json:"topicid" versions:"0-999"`
	// The partitions.
	Partitions []int32 `json:"partitions" versions:"0-999"`
	// Tagged fields (for flexible versions)
	_tagged_fields map[uint32]interface{} `json:"-"`
}

// writeTaggedFields writes tagged fields for ConsumerGroupHeartbeatRequestTopicPartitions.
func (m *ConsumerGroupHeartbeatRequestTopicPartitions) writeTaggedFields(w io.Writer, version int16) error {
	var taggedFieldsCount int
	var taggedFieldsBuf bytes.Buffer

	// Write tagged fields count
	if err := protocol.WriteVaruint32(w, uint32(taggedFieldsCount)); err != nil {
		return err
	}

	// Write tagged fields data
	if taggedFieldsCount > 0 {
		if _, err := w.Write(taggedFieldsBuf.Bytes()); err != nil {
			return err
		}
	}

	return nil
}

// readTaggedFields reads tagged fields for ConsumerGroupHeartbeatRequestTopicPartitions.
func (m *ConsumerGroupHeartbeatRequestTopicPartitions) readTaggedFields(r io.Reader, version int16) error {
	// Read tagged fields count
	count, err := protocol.ReadVaruint32(r)
	if err != nil {
		return err
	}

	if count == 0 {
		return nil
	}

	// Read tagged fields
	for i := uint32(0); i < count; i++ {
		tag, err := protocol.ReadVaruint32(r)
		if err != nil {
			return err
		}

		switch tag {
		default:
			// Unknown tag, skip it
		}
	}

	return nil
}

// TopicPartitions represents .
type TopicPartitions struct {
	// The topic ID.
	TopicId uuid.UUID `json:"topicid" versions:"0-999"`
	// The partitions.
	Partitions []int32 `json:"partitions" versions:"0-999"`
}

// writeTaggedFields writes tagged fields for ConsumerGroupHeartbeatRequest.
func (m *ConsumerGroupHeartbeatRequest) writeTaggedFields(w io.Writer, version int16) error {
	var taggedFieldsCount int
	var taggedFieldsBuf bytes.Buffer

	// Write tagged fields count
	if err := protocol.WriteVaruint32(w, uint32(taggedFieldsCount)); err != nil {
		return err
	}

	// Write tagged fields data
	if taggedFieldsCount > 0 {
		if _, err := w.Write(taggedFieldsBuf.Bytes()); err != nil {
			return err
		}
	}

	return nil
}

// readTaggedFields reads tagged fields for ConsumerGroupHeartbeatRequest.
func (m *ConsumerGroupHeartbeatRequest) readTaggedFields(r io.Reader, version int16) error {
	// Read tagged fields count
	count, err := protocol.ReadVaruint32(r)
	if err != nil {
		return err
	}

	if count == 0 {
		return nil
	}

	// Read tagged fields
	for i := uint32(0); i < count; i++ {
		tag, err := protocol.ReadVaruint32(r)
		if err != nil {
			return err
		}

		switch tag {
		default:
			// Unknown tag, skip it
			// Read and discard the field data
			// For now, we'll need to know the type to skip properly
			// This is a simplified implementation
		}
	}

	return nil
}
