package consumergroupheartbeat

import (
	"bytes"
	"errors"
	"io"

	"github.com/google/uuid"
	"github.com/scholzj/go-kafka-protocol/protocol"
)

const (
	ConsumerGroupHeartbeatResponseApiKey        = 68
	ConsumerGroupHeartbeatResponseHeaderVersion = 1
)

// ConsumerGroupHeartbeatResponse represents a response message.
type ConsumerGroupHeartbeatResponse struct {
	// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
	ThrottleTimeMs int32 `json:"throttletimems" versions:"0-999"`
	// The top-level error code, or 0 if there was no error.
	ErrorCode int16 `json:"errorcode" versions:"0-999"`
	// The top-level error message, or null if there was no error.
	ErrorMessage *string `json:"errormessage" versions:"0-999"`
	// The member id is generated by the consumer starting from version 1, while in version 0, it can be provided by users or generated by the group coordinator.
	MemberId *string `json:"memberid" versions:"0-999"`
	// The member epoch.
	MemberEpoch int32 `json:"memberepoch" versions:"0-999"`
	// The heartbeat interval in milliseconds.
	HeartbeatIntervalMs int32 `json:"heartbeatintervalms" versions:"0-999"`
	// null if not provided; the assignment otherwise.
	Assignment ConsumerGroupHeartbeatResponseAssignment `json:"assignment" versions:"0-999"`
}

// Encode encodes a ConsumerGroupHeartbeatResponse to a byte slice for the given version.
func (m *ConsumerGroupHeartbeatResponse) Encode(version int16) ([]byte, error) {
	var buf bytes.Buffer
	if err := m.Write(&buf, version); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Decode decodes a ConsumerGroupHeartbeatResponse from a byte slice for the given version.
func (m *ConsumerGroupHeartbeatResponse) Decode(data []byte, version int16) error {
	r := bytes.NewReader(data)
	return m.Read(r, version)
}

// Write writes a ConsumerGroupHeartbeatResponse to an io.Writer for the given version.
func (m *ConsumerGroupHeartbeatResponse) Write(w io.Writer, version int16) error {
	if version < 0 || version > 1 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// ThrottleTimeMs
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.ThrottleTimeMs); err != nil {
			return err
		}
	}
	// ErrorCode
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt16(w, m.ErrorCode); err != nil {
			return err
		}
	}
	// ErrorMessage
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.ErrorMessage); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.ErrorMessage); err != nil {
				return err
			}
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.MemberId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.MemberId); err != nil {
				return err
			}
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.MemberEpoch); err != nil {
			return err
		}
	}
	// HeartbeatIntervalMs
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.HeartbeatIntervalMs); err != nil {
			return err
		}
	}
	// Assignment
	if version >= 0 && version <= 999 {
		// TopicPartitions
		if version >= 0 && version <= 999 {
			// Encode array using ArrayEncoder
			encoder := func(item interface{}) ([]byte, error) {
				if item == nil {
					return nil, nil
				}
				structItem, ok := item.(TopicPartitions)
				if !ok {
					return nil, errors.New("invalid type for array element")
				}
				var elemBuf bytes.Buffer
				// Temporarily use elemBuf as writer
				elemW := &elemBuf
				// TopicId
				if version >= 0 && version <= 999 {
					if err := protocol.WriteUUID(elemW, structItem.TopicId); err != nil {
						return nil, err
					}
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						if err := protocol.WriteCompactInt32Array(elemW, structItem.Partitions); err != nil {
							return nil, err
						}
					} else {
						if err := protocol.WriteInt32Array(elemW, structItem.Partitions); err != nil {
							return nil, err
						}
					}
				}
				return elemBuf.Bytes(), nil
			}
			items := make([]interface{}, len(m.Assignment.TopicPartitions))
			for i := range m.Assignment.TopicPartitions {
				items[i] = m.Assignment.TopicPartitions[i]
			}
			if isFlexible {
				if err := protocol.WriteCompactArray(w, items, encoder); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteArray(w, items, encoder); err != nil {
					return err
				}
			}
		}
		// Write tagged fields if flexible
		if isFlexible {
			if err := m.Assignment.writeTaggedFields(w, version); err != nil {
				return err
			}
		}
	}
	// Write tagged fields if flexible
	if isFlexible {
		if err := m.writeTaggedFields(w, version); err != nil {
			return err
		}
	}
	return nil
}

// Read reads a ConsumerGroupHeartbeatResponse from an io.Reader for the given version.
func (m *ConsumerGroupHeartbeatResponse) Read(r io.Reader, version int16) error {
	if version < 0 || version > 1 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// ThrottleTimeMs
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = val
	}
	// ErrorCode
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt16(r)
		if err != nil {
			return err
		}
		m.ErrorCode = val
	}
	// ErrorMessage
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.ErrorMessage = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.ErrorMessage = val
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.MemberEpoch = val
	}
	// HeartbeatIntervalMs
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.HeartbeatIntervalMs = val
	}
	// Assignment
	if version >= 0 && version <= 999 {
		// TopicPartitions
		if version >= 0 && version <= 999 {
			// Decode array using ArrayDecoder
			decoder := func(data []byte) (interface{}, int, error) {
				var elem TopicPartitions
				elemR := bytes.NewReader(data)
				// TopicId
				if version >= 0 && version <= 999 {
					val, err := protocol.ReadUUID(elemR)
					if err != nil {
						return nil, 0, err
					}
					elem.TopicId = val
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						val, err := protocol.ReadCompactInt32Array(elemR)
						if err != nil {
							return nil, 0, err
						}
						elem.Partitions = val
					} else {
						val, err := protocol.ReadInt32Array(elemR)
						if err != nil {
							return nil, 0, err
						}
						elem.Partitions = val
					}
				}
				consumed := len(data) - elemR.Len()
				return elem, consumed, nil
			}
			if isFlexible {
				lengthUint, err := protocol.ReadVaruint32(r)
				if err != nil {
					return err
				}
				if lengthUint < 1 {
					return errors.New("invalid compact array length")
				}
				length := int32(lengthUint - 1)
				// Collect all array elements into a buffer
				var arrayBuf bytes.Buffer
				for i := int32(0); i < length; i++ {
					// Read element into struct and encode to buffer
					var elemBuf bytes.Buffer
					elemW := &elemBuf
					var tempElem TopicPartitions
					// TopicId
					if version >= 0 && version <= 999 {
						val, err := protocol.ReadUUID(r)
						if err != nil {
							return err
						}
						tempElem.TopicId = val
					}
					// Partitions
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactInt32Array(r)
							if err != nil {
								return err
							}
							tempElem.Partitions = val
						} else {
							val, err := protocol.ReadInt32Array(r)
							if err != nil {
								return err
							}
							tempElem.Partitions = val
						}
					}
					// TopicId
					if version >= 0 && version <= 999 {
						if err := protocol.WriteUUID(elemW, tempElem.TopicId); err != nil {
							return err
						}
					}
					// Partitions
					if version >= 0 && version <= 999 {
						if isFlexible {
							if err := protocol.WriteCompactInt32Array(elemW, tempElem.Partitions); err != nil {
								return err
							}
						} else {
							if err := protocol.WriteInt32Array(elemW, tempElem.Partitions); err != nil {
								return err
							}
						}
					}
					// Append to array buffer
					arrayBuf.Write(elemBuf.Bytes())
				}
				// Prepend length and decode using DecodeCompactArray
				lengthBytes := protocol.EncodeVaruint32(lengthUint)
				fullData := append(lengthBytes, arrayBuf.Bytes()...)
				decoded, _, err := protocol.DecodeCompactArray(fullData, decoder)
				if err != nil {
					return err
				}
				// Convert []interface{} to typed slice
				m.Assignment.TopicPartitions = make([]TopicPartitions, len(decoded))
				for i, item := range decoded {
					m.Assignment.TopicPartitions[i] = item.(TopicPartitions)
				}
			} else {
				length, err := protocol.ReadInt32(r)
				if err != nil {
					return err
				}
				// Collect all array elements into a buffer
				var arrayBuf bytes.Buffer
				for i := int32(0); i < length; i++ {
					// Read element into struct and encode to buffer
					var elemBuf bytes.Buffer
					elemW := &elemBuf
					var tempElem TopicPartitions
					// TopicId
					if version >= 0 && version <= 999 {
						val, err := protocol.ReadUUID(r)
						if err != nil {
							return err
						}
						tempElem.TopicId = val
					}
					// Partitions
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactInt32Array(r)
							if err != nil {
								return err
							}
							tempElem.Partitions = val
						} else {
							val, err := protocol.ReadInt32Array(r)
							if err != nil {
								return err
							}
							tempElem.Partitions = val
						}
					}
					// TopicId
					if version >= 0 && version <= 999 {
						if err := protocol.WriteUUID(elemW, tempElem.TopicId); err != nil {
							return err
						}
					}
					// Partitions
					if version >= 0 && version <= 999 {
						if isFlexible {
							if err := protocol.WriteCompactInt32Array(elemW, tempElem.Partitions); err != nil {
								return err
							}
						} else {
							if err := protocol.WriteInt32Array(elemW, tempElem.Partitions); err != nil {
								return err
							}
						}
					}
					// Append to array buffer
					arrayBuf.Write(elemBuf.Bytes())
				}
				// Prepend length and decode using DecodeArray
				lengthBytes := protocol.EncodeInt32(length)
				fullData := append(lengthBytes, arrayBuf.Bytes()...)
				decoded, _, err := protocol.DecodeArray(fullData, decoder)
				if err != nil {
					return err
				}
				// Convert []interface{} to typed slice
				m.Assignment.TopicPartitions = make([]TopicPartitions, len(decoded))
				for i, item := range decoded {
					m.Assignment.TopicPartitions[i] = item.(TopicPartitions)
				}
			}
		}
		// Read tagged fields if flexible
		if isFlexible {
			if err := m.Assignment.readTaggedFields(r, version); err != nil {
				return err
			}
		}
	}
	// Read tagged fields if flexible
	if isFlexible {
		if err := m.readTaggedFields(r, version); err != nil {
			return err
		}
	}
	return nil
}

// ConsumerGroupHeartbeatResponseAssignment represents null if not provided; the assignment otherwise..
type ConsumerGroupHeartbeatResponseAssignment struct {
	// The partitions assigned to the member that can be used immediately.
	TopicPartitions []TopicPartitions `json:"topicpartitions" versions:"0-999"`
	// Tagged fields (for flexible versions)
	_tagged_fields map[uint32]interface{} `json:"-"`
}

// writeTaggedFields writes tagged fields for ConsumerGroupHeartbeatResponseAssignment.
func (m *ConsumerGroupHeartbeatResponseAssignment) writeTaggedFields(w io.Writer, version int16) error {
	var taggedFieldsCount int
	var taggedFieldsBuf bytes.Buffer

	// Write tagged fields count
	if err := protocol.WriteVaruint32(w, uint32(taggedFieldsCount)); err != nil {
		return err
	}

	// Write tagged fields data
	if taggedFieldsCount > 0 {
		if _, err := w.Write(taggedFieldsBuf.Bytes()); err != nil {
			return err
		}
	}

	return nil
}

// readTaggedFields reads tagged fields for ConsumerGroupHeartbeatResponseAssignment.
func (m *ConsumerGroupHeartbeatResponseAssignment) readTaggedFields(r io.Reader, version int16) error {
	// Read tagged fields count
	count, err := protocol.ReadVaruint32(r)
	if err != nil {
		return err
	}

	if count == 0 {
		return nil
	}

	// Read tagged fields
	for i := uint32(0); i < count; i++ {
		tag, err := protocol.ReadVaruint32(r)
		if err != nil {
			return err
		}

		switch tag {
		default:
			// Unknown tag, skip it
		}
	}

	return nil
}

// writeTaggedFields writes tagged fields for ConsumerGroupHeartbeatResponse.
func (m *ConsumerGroupHeartbeatResponse) writeTaggedFields(w io.Writer, version int16) error {
	var taggedFieldsCount int
	var taggedFieldsBuf bytes.Buffer

	// Write tagged fields count
	if err := protocol.WriteVaruint32(w, uint32(taggedFieldsCount)); err != nil {
		return err
	}

	// Write tagged fields data
	if taggedFieldsCount > 0 {
		if _, err := w.Write(taggedFieldsBuf.Bytes()); err != nil {
			return err
		}
	}

	return nil
}

// readTaggedFields reads tagged fields for ConsumerGroupHeartbeatResponse.
func (m *ConsumerGroupHeartbeatResponse) readTaggedFields(r io.Reader, version int16) error {
	// Read tagged fields count
	count, err := protocol.ReadVaruint32(r)
	if err != nil {
		return err
	}

	if count == 0 {
		return nil
	}

	// Read tagged fields
	for i := uint32(0); i < count; i++ {
		tag, err := protocol.ReadVaruint32(r)
		if err != nil {
			return err
		}

		switch tag {
		default:
			// Unknown tag, skip it
			// Read and discard the field data
			// For now, we'll need to know the type to skip properly
			// This is a simplified implementation
		}
	}

	return nil
}
