package consumergroupheartbeat

import (
	"bytes"
	"fmt"
	"github.com/google/uuid"
	"github.com/scholzj/go-kafka-protocol/protocol"
	"io"
)

type ConsumerGroupHeartbeatRequest struct {
	ApiVersion           int16
	GroupId              *string                                        // The group identifier. (versions: 0+)
	MemberId             *string                                        // The member id generated by the consumer. The member id must be kept during the entire lifetime of the consumer process. (versions: 0+)
	MemberEpoch          int32                                          // The current member epoch; 0 to join the group; -1 to leave the group; -2 to indicate that the static member will rejoin. (versions: 0+)
	InstanceId           *string                                        // null if not provided or if it didn't change since the last heartbeat; the instance Id otherwise. (versions: 0+, nullable: 0+)
	RackId               *string                                        // null if not provided or if it didn't change since the last heartbeat; the rack ID of consumer otherwise. (versions: 0+, nullable: 0+)
	RebalanceTimeoutMs   int32                                          // -1 if it didn't change since the last heartbeat; the maximum time in milliseconds that the coordinator will wait on the member to revoke its partitions otherwise. (versions: 0+)
	SubscribedTopicNames *[]string                                      // null if it didn't change since the last heartbeat; the subscribed topic names otherwise. (versions: 0+, nullable: 0+)
	SubscribedTopicRegex *string                                        // null if it didn't change since the last heartbeat; the subscribed topic regex otherwise. (versions: 1+, nullable: 1+)
	ServerAssignor       *string                                        // null if not used or if it didn't change since the last heartbeat; the server side assignor to use otherwise. (versions: 0+, nullable: 0+)
	TopicPartitions      *[]ConsumerGroupHeartbeatRequestTopicPartition // null if it didn't change since the last heartbeat; the partitions owned by the member. (versions: 0+, nullable: 0+)
	rawTaggedFields      *[]protocol.TaggedField
}

type ConsumerGroupHeartbeatRequestTopicPartition struct {
	TopicId         uuid.UUID // The topic ID. (versions: 0+)
	Partitions      *[]int32  // The partitions. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

func isRequestFlexible(apiVersion int16) bool {
	return apiVersion >= 0
}

func (req *ConsumerGroupHeartbeatRequest) Write(w io.Writer) error {
	// GroupId (versions: 0+)
	if req.GroupId == nil {
		return fmt.Errorf("ConsumerGroupHeartbeatRequest.GroupId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *req.GroupId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *req.GroupId); err != nil {
			return err
		}
	}

	// MemberId (versions: 0+)
	if req.MemberId == nil {
		return fmt.Errorf("ConsumerGroupHeartbeatRequest.MemberId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *req.MemberId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *req.MemberId); err != nil {
			return err
		}
	}

	// MemberEpoch (versions: 0+)
	if err := protocol.WriteInt32(w, req.MemberEpoch); err != nil {
		return err
	}

	// InstanceId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, req.InstanceId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, req.InstanceId); err != nil {
			return err
		}
	}

	// RackId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, req.RackId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, req.RackId); err != nil {
			return err
		}
	}

	// RebalanceTimeoutMs (versions: 0+)
	if err := protocol.WriteInt32(w, req.RebalanceTimeoutMs); err != nil {
		return err
	}

	// SubscribedTopicNames (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteCompactString, req.SubscribedTopicNames); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, protocol.WriteString, req.SubscribedTopicNames); err != nil {
			return err
		}
	}

	// SubscribedTopicRegex (versions: 1+)
	if req.ApiVersion >= 1 {
		if isRequestFlexible(req.ApiVersion) {
			if err := protocol.WriteNullableCompactString(w, req.SubscribedTopicRegex); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, req.SubscribedTopicRegex); err != nil {
				return err
			}
		}
	}

	// ServerAssignor (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, req.ServerAssignor); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, req.ServerAssignor); err != nil {
			return err
		}
	}

	// TopicPartitions (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.topicPartitionsEncoder, req.TopicPartitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, req.topicPartitionsEncoder, req.TopicPartitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if req.rawTaggedFields != nil {
			rawTaggedFields = *req.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

// TODO: pass version and bytes only
func (req *ConsumerGroupHeartbeatRequest) Read(request *protocol.Request) error {
	if request == nil || request.Body == nil {
		return fmt.Errorf("ConsumerGroupHeartbeatRequest.Read: request or its body is nil")
	}

	r := bytes.NewBuffer(request.Body.Bytes())
	req.ApiVersion = request.ApiVersion

	// GroupId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		groupid, err := protocol.ReadCompactString(r)
		if err != nil {
			return err
		}
		req.GroupId = &groupid
	} else {
		groupid, err := protocol.ReadString(r)
		if err != nil {
			return err
		}
		req.GroupId = &groupid
	}

	// MemberId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		memberid, err := protocol.ReadCompactString(r)
		if err != nil {
			return err
		}
		req.MemberId = &memberid
	} else {
		memberid, err := protocol.ReadString(r)
		if err != nil {
			return err
		}
		req.MemberId = &memberid
	}

	// MemberEpoch (versions: 0+)
	memberepoch, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	req.MemberEpoch = memberepoch

	// InstanceId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		instanceid, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		req.InstanceId = instanceid
	} else {
		instanceid, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		req.InstanceId = instanceid
	}

	// RackId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		rackid, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		req.RackId = rackid
	} else {
		rackid, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		req.RackId = rackid
	}

	// RebalanceTimeoutMs (versions: 0+)
	rebalancetimeoutms, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	req.RebalanceTimeoutMs = rebalancetimeoutms

	// SubscribedTopicNames (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subscribedtopicnames, err := protocol.ReadNullableCompactArray(r, protocol.ReadCompactString)
		if err != nil {
			return err
		}
		req.SubscribedTopicNames = subscribedtopicnames
	} else {
		subscribedtopicnames, err := protocol.ReadNullableArray(r, protocol.ReadString)
		if err != nil {
			return err
		}
		req.SubscribedTopicNames = subscribedtopicnames
	}

	// SubscribedTopicRegex (versions: 1+)
	if req.ApiVersion >= 1 {
		if isRequestFlexible(req.ApiVersion) {
			subscribedtopicregex, err := protocol.ReadNullableCompactString(r)
			if err != nil {
				return err
			}
			req.SubscribedTopicRegex = subscribedtopicregex
		} else {
			subscribedtopicregex, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			req.SubscribedTopicRegex = subscribedtopicregex
		}
	}

	// ServerAssignor (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		serverassignor, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		req.ServerAssignor = serverassignor
	} else {
		serverassignor, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		req.ServerAssignor = serverassignor
	}

	// TopicPartitions (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		topicpartitions, err := protocol.ReadNullableCompactArray(r, req.topicPartitionsDecoder)
		if err != nil {
			return err
		}
		req.TopicPartitions = topicpartitions
	} else {
		topicpartitions, err := protocol.ReadNullableArray(r, req.topicPartitionsDecoder)
		if err != nil {
			return err
		}
		req.TopicPartitions = topicpartitions
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return err
		}
		req.rawTaggedFields = &rawTaggedFields
	}

	return nil
}

func (req *ConsumerGroupHeartbeatRequest) topicPartitionsEncoder(w io.Writer, value ConsumerGroupHeartbeatRequestTopicPartition) error {
	// TopicId (versions: 0+)
	if err := protocol.WriteUUID(w, value.TopicId); err != nil {
		return err
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("ConsumerGroupHeartbeatRequestTopicPartition.Partitions must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *ConsumerGroupHeartbeatRequest) topicPartitionsDecoder(r io.Reader) (ConsumerGroupHeartbeatRequestTopicPartition, error) {
	consumergroupheartbeatrequesttopicpartition := ConsumerGroupHeartbeatRequestTopicPartition{}

	// TopicId (versions: 0+)
	topicid, err := protocol.ReadUUID(r)
	if err != nil {
		return consumergroupheartbeatrequesttopicpartition, err
	}
	consumergroupheartbeatrequesttopicpartition.TopicId = topicid

	// Partitions (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return consumergroupheartbeatrequesttopicpartition, err
		}
		consumergroupheartbeatrequesttopicpartition.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return consumergroupheartbeatrequesttopicpartition, err
		}
		consumergroupheartbeatrequesttopicpartition.Partitions = &partitions
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return consumergroupheartbeatrequesttopicpartition, err
		}
		consumergroupheartbeatrequesttopicpartition.rawTaggedFields = &rawTaggedFields
	}

	return consumergroupheartbeatrequesttopicpartition, nil
}

//goland:noinspection GoUnhandledErrorResult
func (req *ConsumerGroupHeartbeatRequest) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "    -> ConsumerGroupHeartbeatRequest:\n")

	if req.GroupId != nil {
		fmt.Fprintf(w, "        GroupId: %v\n", *req.GroupId)
	} else {
		fmt.Fprintf(w, "        GroupId: nil\n")
	}

	if req.MemberId != nil {
		fmt.Fprintf(w, "        MemberId: %v\n", *req.MemberId)
	} else {
		fmt.Fprintf(w, "        MemberId: nil\n")
	}

	fmt.Fprintf(w, "        MemberEpoch: %v\n", req.MemberEpoch)

	if req.InstanceId != nil {
		fmt.Fprintf(w, "        InstanceId: %v\n", *req.InstanceId)
	} else {
		fmt.Fprintf(w, "        InstanceId: nil\n")
	}

	if req.RackId != nil {
		fmt.Fprintf(w, "        RackId: %v\n", *req.RackId)
	} else {
		fmt.Fprintf(w, "        RackId: nil\n")
	}

	fmt.Fprintf(w, "        RebalanceTimeoutMs: %v\n", req.RebalanceTimeoutMs)

	if req.SubscribedTopicNames != nil {
		fmt.Fprintf(w, "        SubscribedTopicNames: %v\n", *req.SubscribedTopicNames)
	} else {
		fmt.Fprintf(w, "        SubscribedTopicNames: nil\n")
	}

	if req.SubscribedTopicRegex != nil {
		fmt.Fprintf(w, "        SubscribedTopicRegex: %v\n", *req.SubscribedTopicRegex)
	} else {
		fmt.Fprintf(w, "        SubscribedTopicRegex: nil\n")
	}

	if req.ServerAssignor != nil {
		fmt.Fprintf(w, "        ServerAssignor: %v\n", *req.ServerAssignor)
	} else {
		fmt.Fprintf(w, "        ServerAssignor: nil\n")
	}

	if req.TopicPartitions != nil {
		fmt.Fprintf(w, "        TopicPartitions:\n")
		for _, topicpartitions := range *req.TopicPartitions {
			fmt.Fprintf(w, "%s", topicpartitions.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        TopicPartitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *ConsumerGroupHeartbeatRequestTopicPartition) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "            TopicId: %v\n", value.TopicId)

	if value.Partitions != nil {
		fmt.Fprintf(w, "            Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "            Partitions: nil\n")
	}

	return w.String()
}
