package alteruserscramcredentials

import (
	"bytes"
	"fmt"
	"github.com/scholzj/go-kafka-protocol/protocol"
	"io"
)

type AlterUserScramCredentialsRequest struct {
	ApiVersion      int16
	Deletions       *[]AlterUserScramCredentialsRequestDeletion  // The SCRAM credentials to remove. (versions: 0+)
	Upsertions      *[]AlterUserScramCredentialsRequestUpsertion // The SCRAM credentials to update/insert. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type AlterUserScramCredentialsRequestDeletion struct {
	Name            *string // The user name. (versions: 0+)
	Mechanism       int8    // The SCRAM mechanism. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type AlterUserScramCredentialsRequestUpsertion struct {
	Name            *string // The user name. (versions: 0+)
	Mechanism       int8    // The SCRAM mechanism. (versions: 0+)
	Iterations      int32   // The number of iterations. (versions: 0+)
	Salt            *[]byte // A random salt generated by the client. (versions: 0+)
	SaltedPassword  *[]byte // The salted password. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

func isRequestFlexible(apiVersion int16) bool {
	return apiVersion >= 0
}

func (req *AlterUserScramCredentialsRequest) Write(w io.Writer) error {
	// Deletions (versions: 0+)
	if req.Deletions == nil {
		return fmt.Errorf("AlterUserScramCredentialsRequest.Deletions must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.deletionsEncoder, req.Deletions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, req.deletionsEncoder, *req.Deletions); err != nil {
			return err
		}
	}

	// Upsertions (versions: 0+)
	if req.Upsertions == nil {
		return fmt.Errorf("AlterUserScramCredentialsRequest.Upsertions must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.upsertionsEncoder, req.Upsertions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, req.upsertionsEncoder, *req.Upsertions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if req.rawTaggedFields != nil {
			rawTaggedFields = *req.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

// TODO: pass version and bytes only
func (req *AlterUserScramCredentialsRequest) Read(request *protocol.Request) error {
	if request == nil || request.Body == nil {
		return fmt.Errorf("AlterUserScramCredentialsRequest.Read: request or its body is nil")
	}

	r := bytes.NewBuffer(request.Body.Bytes())
	req.ApiVersion = request.ApiVersion

	// Deletions (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		deletions, err := protocol.ReadNullableCompactArray(r, req.deletionsDecoder)
		if err != nil {
			return err
		}
		req.Deletions = deletions
	} else {
		deletions, err := protocol.ReadArray(r, req.deletionsDecoder)
		if err != nil {
			return err
		}
		req.Deletions = &deletions
	}

	// Upsertions (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		upsertions, err := protocol.ReadNullableCompactArray(r, req.upsertionsDecoder)
		if err != nil {
			return err
		}
		req.Upsertions = upsertions
	} else {
		upsertions, err := protocol.ReadArray(r, req.upsertionsDecoder)
		if err != nil {
			return err
		}
		req.Upsertions = &upsertions
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return err
		}
		req.rawTaggedFields = &rawTaggedFields
	}

	return nil
}

func (req *AlterUserScramCredentialsRequest) deletionsEncoder(w io.Writer, value AlterUserScramCredentialsRequestDeletion) error {
	// Name (versions: 0+)
	if value.Name == nil {
		return fmt.Errorf("AlterUserScramCredentialsRequestDeletion.Name must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Name); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Name); err != nil {
			return err
		}
	}

	// Mechanism (versions: 0+)
	if err := protocol.WriteInt8(w, value.Mechanism); err != nil {
		return err
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *AlterUserScramCredentialsRequest) deletionsDecoder(r io.Reader) (AlterUserScramCredentialsRequestDeletion, error) {
	alteruserscramcredentialsrequestdeletion := AlterUserScramCredentialsRequestDeletion{}

	// Name (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		name, err := protocol.ReadCompactString(r)
		if err != nil {
			return alteruserscramcredentialsrequestdeletion, err
		}
		alteruserscramcredentialsrequestdeletion.Name = &name
	} else {
		name, err := protocol.ReadString(r)
		if err != nil {
			return alteruserscramcredentialsrequestdeletion, err
		}
		alteruserscramcredentialsrequestdeletion.Name = &name
	}

	// Mechanism (versions: 0+)
	mechanism, err := protocol.ReadInt8(r)
	if err != nil {
		return alteruserscramcredentialsrequestdeletion, err
	}
	alteruserscramcredentialsrequestdeletion.Mechanism = mechanism

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return alteruserscramcredentialsrequestdeletion, err
		}
		alteruserscramcredentialsrequestdeletion.rawTaggedFields = &rawTaggedFields
	}

	return alteruserscramcredentialsrequestdeletion, nil
}

func (req *AlterUserScramCredentialsRequest) upsertionsEncoder(w io.Writer, value AlterUserScramCredentialsRequestUpsertion) error {
	// Name (versions: 0+)
	if value.Name == nil {
		return fmt.Errorf("AlterUserScramCredentialsRequestUpsertion.Name must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Name); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Name); err != nil {
			return err
		}
	}

	// Mechanism (versions: 0+)
	if err := protocol.WriteInt8(w, value.Mechanism); err != nil {
		return err
	}

	// Iterations (versions: 0+)
	if err := protocol.WriteInt32(w, value.Iterations); err != nil {
		return err
	}

	// Salt (versions: 0+)
	if value.Salt == nil {
		return fmt.Errorf("AlterUserScramCredentialsRequestUpsertion.Salt must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactBytes(w, *value.Salt); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteBytes(w, *value.Salt); err != nil {
			return err
		}
	}

	// SaltedPassword (versions: 0+)
	if value.SaltedPassword == nil {
		return fmt.Errorf("AlterUserScramCredentialsRequestUpsertion.SaltedPassword must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactBytes(w, *value.SaltedPassword); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteBytes(w, *value.SaltedPassword); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *AlterUserScramCredentialsRequest) upsertionsDecoder(r io.Reader) (AlterUserScramCredentialsRequestUpsertion, error) {
	alteruserscramcredentialsrequestupsertion := AlterUserScramCredentialsRequestUpsertion{}

	// Name (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		name, err := protocol.ReadCompactString(r)
		if err != nil {
			return alteruserscramcredentialsrequestupsertion, err
		}
		alteruserscramcredentialsrequestupsertion.Name = &name
	} else {
		name, err := protocol.ReadString(r)
		if err != nil {
			return alteruserscramcredentialsrequestupsertion, err
		}
		alteruserscramcredentialsrequestupsertion.Name = &name
	}

	// Mechanism (versions: 0+)
	mechanism, err := protocol.ReadInt8(r)
	if err != nil {
		return alteruserscramcredentialsrequestupsertion, err
	}
	alteruserscramcredentialsrequestupsertion.Mechanism = mechanism

	// Iterations (versions: 0+)
	iterations, err := protocol.ReadInt32(r)
	if err != nil {
		return alteruserscramcredentialsrequestupsertion, err
	}
	alteruserscramcredentialsrequestupsertion.Iterations = iterations

	// Salt (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		salt, err := protocol.ReadCompactBytes(r)
		if err != nil {
			return alteruserscramcredentialsrequestupsertion, err
		}
		alteruserscramcredentialsrequestupsertion.Salt = &salt
	} else {
		salt, err := protocol.ReadBytes(r)
		if err != nil {
			return alteruserscramcredentialsrequestupsertion, err
		}
		alteruserscramcredentialsrequestupsertion.Salt = &salt
	}

	// SaltedPassword (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		saltedpassword, err := protocol.ReadCompactBytes(r)
		if err != nil {
			return alteruserscramcredentialsrequestupsertion, err
		}
		alteruserscramcredentialsrequestupsertion.SaltedPassword = &saltedpassword
	} else {
		saltedpassword, err := protocol.ReadBytes(r)
		if err != nil {
			return alteruserscramcredentialsrequestupsertion, err
		}
		alteruserscramcredentialsrequestupsertion.SaltedPassword = &saltedpassword
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return alteruserscramcredentialsrequestupsertion, err
		}
		alteruserscramcredentialsrequestupsertion.rawTaggedFields = &rawTaggedFields
	}

	return alteruserscramcredentialsrequestupsertion, nil
}

//goland:noinspection GoUnhandledErrorResult
func (req *AlterUserScramCredentialsRequest) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "    -> AlterUserScramCredentialsRequest:\n")

	if req.Deletions != nil {
		fmt.Fprintf(w, "        Deletions:\n")
		for _, deletions := range *req.Deletions {
			fmt.Fprintf(w, "%s", deletions.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        Deletions: nil\n")
	}

	if req.Upsertions != nil {
		fmt.Fprintf(w, "        Upsertions:\n")
		for _, upsertions := range *req.Upsertions {
			fmt.Fprintf(w, "%s", upsertions.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        Upsertions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *AlterUserScramCredentialsRequestDeletion) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Name != nil {
		fmt.Fprintf(w, "            Name: %v\n", *value.Name)
	} else {
		fmt.Fprintf(w, "            Name: nil\n")
	}

	fmt.Fprintf(w, "            Mechanism: %v\n", value.Mechanism)

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *AlterUserScramCredentialsRequestUpsertion) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Name != nil {
		fmt.Fprintf(w, "            Name: %v\n", *value.Name)
	} else {
		fmt.Fprintf(w, "            Name: nil\n")
	}

	fmt.Fprintf(w, "            Mechanism: %v\n", value.Mechanism)
	fmt.Fprintf(w, "            Iterations: %v\n", value.Iterations)

	if value.Salt != nil {
		fmt.Fprintf(w, "            Salt: <%d bytes>\n", len(*value.Salt))
	} else {
		fmt.Fprintf(w, "            Salt: nil\n")
	}

	if value.SaltedPassword != nil {
		fmt.Fprintf(w, "            SaltedPassword: <%d bytes>\n", len(*value.SaltedPassword))
	} else {
		fmt.Fprintf(w, "            SaltedPassword: nil\n")
	}

	return w.String()
}
