package streamsgroupheartbeat

import (
	"bytes"
	"fmt"
	"github.com/scholzj/go-kafka-protocol/protocol"
	"io"
)

type StreamsGroupHeartbeatRequest struct {
	ApiVersion               int16
	GroupId                  *string                                      // The group identifier. (versions: 0+)
	MemberId                 *string                                      // The member ID generated by the streams consumer. The member ID must be kept during the entire lifetime of the streams consumer process. (versions: 0+)
	MemberEpoch              int32                                        // The current member epoch; 0 to join the group; -1 to leave the group; -2 to indicate that the static member will rejoin. (versions: 0+)
	EndpointInformationEpoch int32                                        // The current endpoint epoch of this client, represents the latest endpoint epoch this client received (versions: 0+)
	InstanceId               *string                                      // null if not provided or if it didn't change since the last heartbeat; the instance ID for static membership otherwise. (versions: 0+, nullable: 0+)
	RackId                   *string                                      // null if not provided or if it didn't change since the last heartbeat; the rack ID of the member otherwise. (versions: 0+, nullable: 0+)
	RebalanceTimeoutMs       int32                                        // -1 if it didn't change since the last heartbeat; the maximum time in milliseconds that the coordinator will wait on the member to revoke its tasks otherwise. (versions: 0+)
	Topology                 *StreamsGroupHeartbeatRequestTopology        // The topology metadata of the streams application. Used to initialize the topology of the group and to check if the topology corresponds to the topology initialized for the group. Only sent when memberEpoch = 0, must be non-empty. Null otherwise. (versions: 0+, nullable: 0+)
	ActiveTasks              *[]StreamsGroupHeartbeatRequestActiveTask    // Currently owned active tasks for this client. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	StandbyTasks             *[]StreamsGroupHeartbeatRequestStandbyTask   // Currently owned standby tasks for this client. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	WarmupTasks              *[]StreamsGroupHeartbeatRequestWarmupTask    // Currently owned warm-up tasks for this client. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	ProcessId                *string                                      // Identity of the streams instance that may have multiple consumers. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	UserEndpoint             *StreamsGroupHeartbeatRequestUserEndpoint    // User-defined endpoint for Interactive Queries. Null if unchanged since last heartbeat, or if not defined on the client. (versions: 0+, nullable: 0+)
	ClientTags               *[]StreamsGroupHeartbeatRequestClientTag     // Used for rack-aware assignment algorithm. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	TaskOffsets              *[]StreamsGroupHeartbeatRequestTaskOffset    // Cumulative changelog offsets for tasks. Only updated when a warm-up task has caught up, and according to the task offset interval. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	TaskEndOffsets           *[]StreamsGroupHeartbeatRequestTaskEndOffset // Cumulative changelog end-offsets for tasks. Only updated when a warm-up task has caught up, and according to the task offset interval. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	ShutdownApplication      bool                                         // Whether all Streams clients in the group should shut down. (versions: 0+)
	rawTaggedFields          *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTopology struct {
	Epoch           int32                                               // The epoch of the topology. Used to check if the topology corresponds to the topology initialized on the brokers. (versions: 0+)
	Subtopologies   *[]StreamsGroupHeartbeatRequestTopologySubtopologie // The sub-topologies of the streams application. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTopologySubtopologie struct {
	SubtopologyId           *string                                                                   // String to uniquely identify the subtopology. Deterministically generated from the topology (versions: 0+)
	SourceTopics            *[]string                                                                 // The topics the topology reads from. (versions: 0+)
	SourceTopicRegex        *[]string                                                                 // The regular expressions identifying topics the subtopology reads from. (versions: 0+)
	StateChangelogTopics    *[]StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopic    // The set of state changelog topics associated with this subtopology. Created automatically. (versions: 0+)
	RepartitionSinkTopics   *[]string                                                                 // The repartition topics the subtopology writes to. (versions: 0+)
	RepartitionSourceTopics *[]StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopic // The set of source topics that are internally created repartition topics. Created automatically. (versions: 0+)
	CopartitionGroups       *[]StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup       // A subset of source topics that must be copartitioned. (versions: 0+)
	rawTaggedFields         *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopic struct {
	Name              *string                                                                           // The name of the topic. (versions: 0+)
	Partitions        int32                                                                             // The number of partitions in the topic. Can be 0 if no specific number of partitions is enforced. Always 0 for changelog topics. (versions: 0+)
	ReplicationFactor int16                                                                             // The replication factor of the topic. Can be 0 if the default replication factor should be used. (versions: 0+)
	TopicConfigs      *[]StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopicTopicConfig // Topic-level configurations as key-value pairs. (versions: 0+)
	rawTaggedFields   *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopicTopicConfig struct {
	Key             *string // key of the config (versions: 0+)
	Value           *string // value of the config (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopic struct {
	Name              *string                                                                              // The name of the topic. (versions: 0+)
	Partitions        int32                                                                                // The number of partitions in the topic. Can be 0 if no specific number of partitions is enforced. Always 0 for changelog topics. (versions: 0+)
	ReplicationFactor int16                                                                                // The replication factor of the topic. Can be 0 if the default replication factor should be used. (versions: 0+)
	TopicConfigs      *[]StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfig // Topic-level configurations as key-value pairs. (versions: 0+)
	rawTaggedFields   *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfig struct {
	Key             *string // key of the config (versions: 0+)
	Value           *string // value of the config (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup struct {
	SourceTopics            *[]int16 // The topics the topology reads from. Index into the array on the subtopology level. (versions: 0+)
	SourceTopicRegex        *[]int16 // Regular expressions identifying topics the subtopology reads from. Index into the array on the subtopology level. (versions: 0+)
	RepartitionSourceTopics *[]int16 // The set of source topics that are internally created repartition topics. Index into the array on the subtopology level. (versions: 0+)
	rawTaggedFields         *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestActiveTask struct {
	SubtopologyId   *string  // The subtopology identifier. (versions: 0+)
	Partitions      *[]int32 // The partitions of the input topics processed by this member. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestStandbyTask struct {
	SubtopologyId   *string  // The subtopology identifier. (versions: 0+)
	Partitions      *[]int32 // The partitions of the input topics processed by this member. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestWarmupTask struct {
	SubtopologyId   *string  // The subtopology identifier. (versions: 0+)
	Partitions      *[]int32 // The partitions of the input topics processed by this member. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestUserEndpoint struct {
	Host            *string // host of the endpoint (versions: 0+)
	Port            uint16  // port of the endpoint (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestClientTag struct {
	Key             *string // key of the config (versions: 0+)
	Value           *string // value of the config (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTaskOffset struct {
	SubtopologyId   *string // The subtopology identifier. (versions: 0+)
	Partition       int32   // The partition. (versions: 0+)
	Offset          int64   // The offset. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatRequestTaskEndOffset struct {
	SubtopologyId   *string // The subtopology identifier. (versions: 0+)
	Partition       int32   // The partition. (versions: 0+)
	Offset          int64   // The offset. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

func isRequestFlexible(apiVersion int16) bool {
	return apiVersion >= 0
}

func (req *StreamsGroupHeartbeatRequest) Write(w io.Writer) error {
	// GroupId (versions: 0+)
	if req.GroupId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequest.GroupId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *req.GroupId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *req.GroupId); err != nil {
			return err
		}
	}

	// MemberId (versions: 0+)
	if req.MemberId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequest.MemberId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *req.MemberId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *req.MemberId); err != nil {
			return err
		}
	}

	// MemberEpoch (versions: 0+)
	if err := protocol.WriteInt32(w, req.MemberEpoch); err != nil {
		return err
	}

	// EndpointInformationEpoch (versions: 0+)
	if err := protocol.WriteInt32(w, req.EndpointInformationEpoch); err != nil {
		return err
	}

	// InstanceId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, req.InstanceId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, req.InstanceId); err != nil {
			return err
		}
	}

	// RackId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, req.RackId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, req.RackId); err != nil {
			return err
		}
	}

	// RebalanceTimeoutMs (versions: 0+)
	if err := protocol.WriteInt32(w, req.RebalanceTimeoutMs); err != nil {
		return err
	}

	// Topology (versions: 0+)
	if err := req.topologyEncoder(w, *req.Topology); err != nil {
		return err
	}

	// ActiveTasks (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.activeTasksEncoder, req.ActiveTasks); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, req.activeTasksEncoder, req.ActiveTasks); err != nil {
			return err
		}
	}

	// StandbyTasks (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.standbyTasksEncoder, req.StandbyTasks); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, req.standbyTasksEncoder, req.StandbyTasks); err != nil {
			return err
		}
	}

	// WarmupTasks (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.warmupTasksEncoder, req.WarmupTasks); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, req.warmupTasksEncoder, req.WarmupTasks); err != nil {
			return err
		}
	}

	// ProcessId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, req.ProcessId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, req.ProcessId); err != nil {
			return err
		}
	}

	// UserEndpoint (versions: 0+)
	if err := req.userEndpointEncoder(w, *req.UserEndpoint); err != nil {
		return err
	}

	// ClientTags (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.clientTagsEncoder, req.ClientTags); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, req.clientTagsEncoder, req.ClientTags); err != nil {
			return err
		}
	}

	// TaskOffsets (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.taskOffsetsEncoder, req.TaskOffsets); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, req.taskOffsetsEncoder, req.TaskOffsets); err != nil {
			return err
		}
	}

	// TaskEndOffsets (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.taskEndOffsetsEncoder, req.TaskEndOffsets); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, req.taskEndOffsetsEncoder, req.TaskEndOffsets); err != nil {
			return err
		}
	}

	// ShutdownApplication (versions: 0+)
	if err := protocol.WriteBool(w, req.ShutdownApplication); err != nil {
		return err
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if req.rawTaggedFields != nil {
			rawTaggedFields = *req.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

// TODO: pass version and bytes only
func (req *StreamsGroupHeartbeatRequest) Read(request *protocol.Request) error {
	if request == nil || request.Body == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequest.Read: request or its body is nil")
	}

	r := bytes.NewBuffer(request.Body.Bytes())
	req.ApiVersion = request.ApiVersion

	// GroupId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		groupid, err := protocol.ReadCompactString(r)
		if err != nil {
			return err
		}
		req.GroupId = &groupid
	} else {
		groupid, err := protocol.ReadString(r)
		if err != nil {
			return err
		}
		req.GroupId = &groupid
	}

	// MemberId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		memberid, err := protocol.ReadCompactString(r)
		if err != nil {
			return err
		}
		req.MemberId = &memberid
	} else {
		memberid, err := protocol.ReadString(r)
		if err != nil {
			return err
		}
		req.MemberId = &memberid
	}

	// MemberEpoch (versions: 0+)
	memberepoch, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	req.MemberEpoch = memberepoch

	// EndpointInformationEpoch (versions: 0+)
	endpointinformationepoch, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	req.EndpointInformationEpoch = endpointinformationepoch

	// InstanceId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		instanceid, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		req.InstanceId = instanceid
	} else {
		instanceid, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		req.InstanceId = instanceid
	}

	// RackId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		rackid, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		req.RackId = rackid
	} else {
		rackid, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		req.RackId = rackid
	}

	// RebalanceTimeoutMs (versions: 0+)
	rebalancetimeoutms, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	req.RebalanceTimeoutMs = rebalancetimeoutms

	// Topology (versions: 0+)
	topology, err := req.topologyDecoder(r)
	if err != nil {
		return err
	}
	req.Topology = &topology

	// ActiveTasks (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		activetasks, err := protocol.ReadNullableCompactArray(r, req.activeTasksDecoder)
		if err != nil {
			return err
		}
		req.ActiveTasks = activetasks
	} else {
		activetasks, err := protocol.ReadNullableArray(r, req.activeTasksDecoder)
		if err != nil {
			return err
		}
		req.ActiveTasks = activetasks
	}

	// StandbyTasks (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		standbytasks, err := protocol.ReadNullableCompactArray(r, req.standbyTasksDecoder)
		if err != nil {
			return err
		}
		req.StandbyTasks = standbytasks
	} else {
		standbytasks, err := protocol.ReadNullableArray(r, req.standbyTasksDecoder)
		if err != nil {
			return err
		}
		req.StandbyTasks = standbytasks
	}

	// WarmupTasks (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		warmuptasks, err := protocol.ReadNullableCompactArray(r, req.warmupTasksDecoder)
		if err != nil {
			return err
		}
		req.WarmupTasks = warmuptasks
	} else {
		warmuptasks, err := protocol.ReadNullableArray(r, req.warmupTasksDecoder)
		if err != nil {
			return err
		}
		req.WarmupTasks = warmuptasks
	}

	// ProcessId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		processid, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		req.ProcessId = processid
	} else {
		processid, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		req.ProcessId = processid
	}

	// UserEndpoint (versions: 0+)
	userendpoint, err := req.userEndpointDecoder(r)
	if err != nil {
		return err
	}
	req.UserEndpoint = &userendpoint

	// ClientTags (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		clienttags, err := protocol.ReadNullableCompactArray(r, req.clientTagsDecoder)
		if err != nil {
			return err
		}
		req.ClientTags = clienttags
	} else {
		clienttags, err := protocol.ReadNullableArray(r, req.clientTagsDecoder)
		if err != nil {
			return err
		}
		req.ClientTags = clienttags
	}

	// TaskOffsets (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		taskoffsets, err := protocol.ReadNullableCompactArray(r, req.taskOffsetsDecoder)
		if err != nil {
			return err
		}
		req.TaskOffsets = taskoffsets
	} else {
		taskoffsets, err := protocol.ReadNullableArray(r, req.taskOffsetsDecoder)
		if err != nil {
			return err
		}
		req.TaskOffsets = taskoffsets
	}

	// TaskEndOffsets (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		taskendoffsets, err := protocol.ReadNullableCompactArray(r, req.taskEndOffsetsDecoder)
		if err != nil {
			return err
		}
		req.TaskEndOffsets = taskendoffsets
	} else {
		taskendoffsets, err := protocol.ReadNullableArray(r, req.taskEndOffsetsDecoder)
		if err != nil {
			return err
		}
		req.TaskEndOffsets = taskendoffsets
	}

	// ShutdownApplication (versions: 0+)
	shutdownapplication, err := protocol.ReadBool(r)
	if err != nil {
		return err
	}
	req.ShutdownApplication = shutdownapplication

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return err
		}
		req.rawTaggedFields = &rawTaggedFields
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) topologyEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTopology) error {
	// Epoch (versions: 0+)
	if err := protocol.WriteInt32(w, value.Epoch); err != nil {
		return err
	}

	// Subtopologies (versions: 0+)
	if value.Subtopologies == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopology.Subtopologies must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.subtopologiesEncoder, value.Subtopologies); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, req.subtopologiesEncoder, *value.Subtopologies); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) topologyDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTopology, error) {
	streamsgroupheartbeatrequesttopology := StreamsGroupHeartbeatRequestTopology{}

	// Epoch (versions: 0+)
	epoch, err := protocol.ReadInt32(r)
	if err != nil {
		return streamsgroupheartbeatrequesttopology, err
	}
	streamsgroupheartbeatrequesttopology.Epoch = epoch

	// Subtopologies (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subtopologies, err := protocol.ReadNullableCompactArray(r, req.subtopologiesDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopology, err
		}
		streamsgroupheartbeatrequesttopology.Subtopologies = subtopologies
	} else {
		subtopologies, err := protocol.ReadArray(r, req.subtopologiesDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopology, err
		}
		streamsgroupheartbeatrequesttopology.Subtopologies = &subtopologies
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopology, err
		}
		streamsgroupheartbeatrequesttopology.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttopology, nil
}

func (req *StreamsGroupHeartbeatRequest) subtopologiesEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTopologySubtopologie) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologie.SubtopologyId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// SourceTopics (versions: 0+)
	if value.SourceTopics == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologie.SourceTopics must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteCompactString, value.SourceTopics); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteString, *value.SourceTopics); err != nil {
			return err
		}
	}

	// SourceTopicRegex (versions: 0+)
	if value.SourceTopicRegex == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologie.SourceTopicRegex must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteCompactString, value.SourceTopicRegex); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteString, *value.SourceTopicRegex); err != nil {
			return err
		}
	}

	// StateChangelogTopics (versions: 0+)
	if value.StateChangelogTopics == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologie.StateChangelogTopics must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.stateChangelogTopicsEncoder, value.StateChangelogTopics); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, req.stateChangelogTopicsEncoder, *value.StateChangelogTopics); err != nil {
			return err
		}
	}

	// RepartitionSinkTopics (versions: 0+)
	if value.RepartitionSinkTopics == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologie.RepartitionSinkTopics must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteCompactString, value.RepartitionSinkTopics); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteString, *value.RepartitionSinkTopics); err != nil {
			return err
		}
	}

	// RepartitionSourceTopics (versions: 0+)
	if value.RepartitionSourceTopics == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologie.RepartitionSourceTopics must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.repartitionSourceTopicsEncoder, value.RepartitionSourceTopics); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, req.repartitionSourceTopicsEncoder, *value.RepartitionSourceTopics); err != nil {
			return err
		}
	}

	// CopartitionGroups (versions: 0+)
	if value.CopartitionGroups == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologie.CopartitionGroups must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.copartitionGroupsEncoder, value.CopartitionGroups); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, req.copartitionGroupsEncoder, *value.CopartitionGroups); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) subtopologiesDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTopologySubtopologie, error) {
	streamsgroupheartbeatrequesttopologysubtopologie := StreamsGroupHeartbeatRequestTopologySubtopologie{}

	// SubtopologyId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.SubtopologyId = &subtopologyid
	}

	// SourceTopics (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		sourcetopics, err := protocol.ReadNullableCompactArray(r, protocol.ReadCompactString)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.SourceTopics = sourcetopics
	} else {
		sourcetopics, err := protocol.ReadArray(r, protocol.ReadString)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.SourceTopics = &sourcetopics
	}

	// SourceTopicRegex (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		sourcetopicregex, err := protocol.ReadNullableCompactArray(r, protocol.ReadCompactString)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.SourceTopicRegex = sourcetopicregex
	} else {
		sourcetopicregex, err := protocol.ReadArray(r, protocol.ReadString)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.SourceTopicRegex = &sourcetopicregex
	}

	// StateChangelogTopics (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		statechangelogtopics, err := protocol.ReadNullableCompactArray(r, req.stateChangelogTopicsDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.StateChangelogTopics = statechangelogtopics
	} else {
		statechangelogtopics, err := protocol.ReadArray(r, req.stateChangelogTopicsDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.StateChangelogTopics = &statechangelogtopics
	}

	// RepartitionSinkTopics (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		repartitionsinktopics, err := protocol.ReadNullableCompactArray(r, protocol.ReadCompactString)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.RepartitionSinkTopics = repartitionsinktopics
	} else {
		repartitionsinktopics, err := protocol.ReadArray(r, protocol.ReadString)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.RepartitionSinkTopics = &repartitionsinktopics
	}

	// RepartitionSourceTopics (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		repartitionsourcetopics, err := protocol.ReadNullableCompactArray(r, req.repartitionSourceTopicsDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.RepartitionSourceTopics = repartitionsourcetopics
	} else {
		repartitionsourcetopics, err := protocol.ReadArray(r, req.repartitionSourceTopicsDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.RepartitionSourceTopics = &repartitionsourcetopics
	}

	// CopartitionGroups (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		copartitiongroups, err := protocol.ReadNullableCompactArray(r, req.copartitionGroupsDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.CopartitionGroups = copartitiongroups
	} else {
		copartitiongroups, err := protocol.ReadArray(r, req.copartitionGroupsDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.CopartitionGroups = &copartitiongroups
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologie, err
		}
		streamsgroupheartbeatrequesttopologysubtopologie.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttopologysubtopologie, nil
}

func (req *StreamsGroupHeartbeatRequest) stateChangelogTopicsEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopic) error {
	// Name (versions: 0+)
	if value.Name == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopic.Name must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Name); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Name); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if err := protocol.WriteInt32(w, value.Partitions); err != nil {
		return err
	}

	// ReplicationFactor (versions: 0+)
	if err := protocol.WriteInt16(w, value.ReplicationFactor); err != nil {
		return err
	}

	// TopicConfigs (versions: 0+)
	if value.TopicConfigs == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopic.TopicConfigs must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.topicConfigsEncoder, value.TopicConfigs); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, req.topicConfigsEncoder, *value.TopicConfigs); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) stateChangelogTopicsDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopic, error) {
	streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic := StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopic{}

	// Name (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		name, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic.Name = &name
	} else {
		name, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic.Name = &name
	}

	// Partitions (versions: 0+)
	partitions, err := protocol.ReadInt32(r)
	if err != nil {
		return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic, err
	}
	streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic.Partitions = partitions

	// ReplicationFactor (versions: 0+)
	replicationfactor, err := protocol.ReadInt16(r)
	if err != nil {
		return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic, err
	}
	streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic.ReplicationFactor = replicationfactor

	// TopicConfigs (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		topicconfigs, err := protocol.ReadNullableCompactArray(r, req.topicConfigsDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic.TopicConfigs = topicconfigs
	} else {
		topicconfigs, err := protocol.ReadArray(r, req.topicConfigsDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic.TopicConfigs = &topicconfigs
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopic, nil
}

func (req *StreamsGroupHeartbeatRequest) topicConfigsEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopicTopicConfig) error {
	// Key (versions: 0+)
	if value.Key == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopicTopicConfig.Key must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Key); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Key); err != nil {
			return err
		}
	}

	// Value (versions: 0+)
	if value.Value == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopicTopicConfig.Value must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Value); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Value); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) topicConfigsDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopicTopicConfig, error) {
	streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig := StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopicTopicConfig{}

	// Key (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		key, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig.Key = &key
	} else {
		key, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig.Key = &key
	}

	// Value (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		value, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig.Value = &value
	} else {
		value, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig.Value = &value
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttopologysubtopologiestatechangelogtopictopicconfig, nil
}

func (req *StreamsGroupHeartbeatRequest) repartitionSourceTopicsEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopic) error {
	// Name (versions: 0+)
	if value.Name == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopic.Name must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Name); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Name); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if err := protocol.WriteInt32(w, value.Partitions); err != nil {
		return err
	}

	// ReplicationFactor (versions: 0+)
	if err := protocol.WriteInt16(w, value.ReplicationFactor); err != nil {
		return err
	}

	// TopicConfigs (versions: 0+)
	if value.TopicConfigs == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopic.TopicConfigs must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, req.streamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfigEncoder, value.TopicConfigs); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, req.streamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfigEncoder, *value.TopicConfigs); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) repartitionSourceTopicsDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopic, error) {
	streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic := StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopic{}

	// Name (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		name, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic.Name = &name
	} else {
		name, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic.Name = &name
	}

	// Partitions (versions: 0+)
	partitions, err := protocol.ReadInt32(r)
	if err != nil {
		return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic, err
	}
	streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic.Partitions = partitions

	// ReplicationFactor (versions: 0+)
	replicationfactor, err := protocol.ReadInt16(r)
	if err != nil {
		return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic, err
	}
	streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic.ReplicationFactor = replicationfactor

	// TopicConfigs (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		topicconfigs, err := protocol.ReadNullableCompactArray(r, req.streamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfigDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic.TopicConfigs = topicconfigs
	} else {
		topicconfigs, err := protocol.ReadArray(r, req.streamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfigDecoder)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic.TopicConfigs = &topicconfigs
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopic, nil
}

func (req *StreamsGroupHeartbeatRequest) streamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfigEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfig) error {
	// Key (versions: 0+)
	if value.Key == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfig.Key must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Key); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Key); err != nil {
			return err
		}
	}

	// Value (versions: 0+)
	if value.Value == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfig.Value must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Value); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Value); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) streamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfigDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfig, error) {
	streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig := StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfig{}

	// Key (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		key, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig.Key = &key
	} else {
		key, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig.Key = &key
	}

	// Value (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		value, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig.Value = &value
	} else {
		value, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig.Value = &value
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig, err
		}
		streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttopologysubtopologierepartitionsourcetopictopicconfig, nil
}

func (req *StreamsGroupHeartbeatRequest) copartitionGroupsEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup) error {
	// SourceTopics (versions: 0+)
	if value.SourceTopics == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup.SourceTopics must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt16, value.SourceTopics); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt16, *value.SourceTopics); err != nil {
			return err
		}
	}

	// SourceTopicRegex (versions: 0+)
	if value.SourceTopicRegex == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup.SourceTopicRegex must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt16, value.SourceTopicRegex); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt16, *value.SourceTopicRegex); err != nil {
			return err
		}
	}

	// RepartitionSourceTopics (versions: 0+)
	if value.RepartitionSourceTopics == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup.RepartitionSourceTopics must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt16, value.RepartitionSourceTopics); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt16, *value.RepartitionSourceTopics); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) copartitionGroupsDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup, error) {
	streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup := StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup{}

	// SourceTopics (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		sourcetopics, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt16)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup.SourceTopics = sourcetopics
	} else {
		sourcetopics, err := protocol.ReadArray(r, protocol.ReadInt16)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup.SourceTopics = &sourcetopics
	}

	// SourceTopicRegex (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		sourcetopicregex, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt16)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup.SourceTopicRegex = sourcetopicregex
	} else {
		sourcetopicregex, err := protocol.ReadArray(r, protocol.ReadInt16)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup.SourceTopicRegex = &sourcetopicregex
	}

	// RepartitionSourceTopics (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		repartitionsourcetopics, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt16)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup.RepartitionSourceTopics = repartitionsourcetopics
	} else {
		repartitionsourcetopics, err := protocol.ReadArray(r, protocol.ReadInt16)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup.RepartitionSourceTopics = &repartitionsourcetopics
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup, err
		}
		streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttopologysubtopologiecopartitiongroup, nil
}

func (req *StreamsGroupHeartbeatRequest) activeTasksEncoder(w io.Writer, value StreamsGroupHeartbeatRequestActiveTask) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestActiveTask.SubtopologyId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestActiveTask.Partitions must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) activeTasksDecoder(r io.Reader) (StreamsGroupHeartbeatRequestActiveTask, error) {
	streamsgroupheartbeatrequestactivetask := StreamsGroupHeartbeatRequestActiveTask{}

	// SubtopologyId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequestactivetask, err
		}
		streamsgroupheartbeatrequestactivetask.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequestactivetask, err
		}
		streamsgroupheartbeatrequestactivetask.SubtopologyId = &subtopologyid
	}

	// Partitions (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatrequestactivetask, err
		}
		streamsgroupheartbeatrequestactivetask.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatrequestactivetask, err
		}
		streamsgroupheartbeatrequestactivetask.Partitions = &partitions
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequestactivetask, err
		}
		streamsgroupheartbeatrequestactivetask.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequestactivetask, nil
}

func (req *StreamsGroupHeartbeatRequest) standbyTasksEncoder(w io.Writer, value StreamsGroupHeartbeatRequestStandbyTask) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestStandbyTask.SubtopologyId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestStandbyTask.Partitions must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) standbyTasksDecoder(r io.Reader) (StreamsGroupHeartbeatRequestStandbyTask, error) {
	streamsgroupheartbeatrequeststandbytask := StreamsGroupHeartbeatRequestStandbyTask{}

	// SubtopologyId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequeststandbytask, err
		}
		streamsgroupheartbeatrequeststandbytask.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequeststandbytask, err
		}
		streamsgroupheartbeatrequeststandbytask.SubtopologyId = &subtopologyid
	}

	// Partitions (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatrequeststandbytask, err
		}
		streamsgroupheartbeatrequeststandbytask.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatrequeststandbytask, err
		}
		streamsgroupheartbeatrequeststandbytask.Partitions = &partitions
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequeststandbytask, err
		}
		streamsgroupheartbeatrequeststandbytask.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequeststandbytask, nil
}

func (req *StreamsGroupHeartbeatRequest) warmupTasksEncoder(w io.Writer, value StreamsGroupHeartbeatRequestWarmupTask) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestWarmupTask.SubtopologyId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestWarmupTask.Partitions must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) warmupTasksDecoder(r io.Reader) (StreamsGroupHeartbeatRequestWarmupTask, error) {
	streamsgroupheartbeatrequestwarmuptask := StreamsGroupHeartbeatRequestWarmupTask{}

	// SubtopologyId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequestwarmuptask, err
		}
		streamsgroupheartbeatrequestwarmuptask.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequestwarmuptask, err
		}
		streamsgroupheartbeatrequestwarmuptask.SubtopologyId = &subtopologyid
	}

	// Partitions (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatrequestwarmuptask, err
		}
		streamsgroupheartbeatrequestwarmuptask.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatrequestwarmuptask, err
		}
		streamsgroupheartbeatrequestwarmuptask.Partitions = &partitions
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequestwarmuptask, err
		}
		streamsgroupheartbeatrequestwarmuptask.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequestwarmuptask, nil
}

func (req *StreamsGroupHeartbeatRequest) userEndpointEncoder(w io.Writer, value StreamsGroupHeartbeatRequestUserEndpoint) error {
	// Host (versions: 0+)
	if value.Host == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestUserEndpoint.Host must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Host); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Host); err != nil {
			return err
		}
	}

	// Port (versions: 0+)
	if err := protocol.WriteUint16(w, value.Port); err != nil {
		return err
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) userEndpointDecoder(r io.Reader) (StreamsGroupHeartbeatRequestUserEndpoint, error) {
	streamsgroupheartbeatrequestuserendpoint := StreamsGroupHeartbeatRequestUserEndpoint{}

	// Host (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		host, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequestuserendpoint, err
		}
		streamsgroupheartbeatrequestuserendpoint.Host = &host
	} else {
		host, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequestuserendpoint, err
		}
		streamsgroupheartbeatrequestuserendpoint.Host = &host
	}

	// Port (versions: 0+)
	port, err := protocol.ReadUInt16(r)
	if err != nil {
		return streamsgroupheartbeatrequestuserendpoint, err
	}
	streamsgroupheartbeatrequestuserendpoint.Port = port

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequestuserendpoint, err
		}
		streamsgroupheartbeatrequestuserendpoint.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequestuserendpoint, nil
}

func (req *StreamsGroupHeartbeatRequest) clientTagsEncoder(w io.Writer, value StreamsGroupHeartbeatRequestClientTag) error {
	// Key (versions: 0+)
	if value.Key == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestClientTag.Key must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Key); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Key); err != nil {
			return err
		}
	}

	// Value (versions: 0+)
	if value.Value == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestClientTag.Value must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Value); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Value); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) clientTagsDecoder(r io.Reader) (StreamsGroupHeartbeatRequestClientTag, error) {
	streamsgroupheartbeatrequestclienttag := StreamsGroupHeartbeatRequestClientTag{}

	// Key (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		key, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequestclienttag, err
		}
		streamsgroupheartbeatrequestclienttag.Key = &key
	} else {
		key, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequestclienttag, err
		}
		streamsgroupheartbeatrequestclienttag.Key = &key
	}

	// Value (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		value, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequestclienttag, err
		}
		streamsgroupheartbeatrequestclienttag.Value = &value
	} else {
		value, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequestclienttag, err
		}
		streamsgroupheartbeatrequestclienttag.Value = &value
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequestclienttag, err
		}
		streamsgroupheartbeatrequestclienttag.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequestclienttag, nil
}

func (req *StreamsGroupHeartbeatRequest) taskOffsetsEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTaskOffset) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTaskOffset.SubtopologyId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// Partition (versions: 0+)
	if err := protocol.WriteInt32(w, value.Partition); err != nil {
		return err
	}

	// Offset (versions: 0+)
	if err := protocol.WriteInt64(w, value.Offset); err != nil {
		return err
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) taskOffsetsDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTaskOffset, error) {
	streamsgroupheartbeatrequesttaskoffset := StreamsGroupHeartbeatRequestTaskOffset{}

	// SubtopologyId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttaskoffset, err
		}
		streamsgroupheartbeatrequesttaskoffset.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttaskoffset, err
		}
		streamsgroupheartbeatrequesttaskoffset.SubtopologyId = &subtopologyid
	}

	// Partition (versions: 0+)
	partition, err := protocol.ReadInt32(r)
	if err != nil {
		return streamsgroupheartbeatrequesttaskoffset, err
	}
	streamsgroupheartbeatrequesttaskoffset.Partition = partition

	// Offset (versions: 0+)
	offset, err := protocol.ReadInt64(r)
	if err != nil {
		return streamsgroupheartbeatrequesttaskoffset, err
	}
	streamsgroupheartbeatrequesttaskoffset.Offset = offset

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttaskoffset, err
		}
		streamsgroupheartbeatrequesttaskoffset.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttaskoffset, nil
}

func (req *StreamsGroupHeartbeatRequest) taskEndOffsetsEncoder(w io.Writer, value StreamsGroupHeartbeatRequestTaskEndOffset) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatRequestTaskEndOffset.SubtopologyId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// Partition (versions: 0+)
	if err := protocol.WriteInt32(w, value.Partition); err != nil {
		return err
	}

	// Offset (versions: 0+)
	if err := protocol.WriteInt64(w, value.Offset); err != nil {
		return err
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (req *StreamsGroupHeartbeatRequest) taskEndOffsetsDecoder(r io.Reader) (StreamsGroupHeartbeatRequestTaskEndOffset, error) {
	streamsgroupheartbeatrequesttaskendoffset := StreamsGroupHeartbeatRequestTaskEndOffset{}

	// SubtopologyId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttaskendoffset, err
		}
		streamsgroupheartbeatrequesttaskendoffset.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatrequesttaskendoffset, err
		}
		streamsgroupheartbeatrequesttaskendoffset.SubtopologyId = &subtopologyid
	}

	// Partition (versions: 0+)
	partition, err := protocol.ReadInt32(r)
	if err != nil {
		return streamsgroupheartbeatrequesttaskendoffset, err
	}
	streamsgroupheartbeatrequesttaskendoffset.Partition = partition

	// Offset (versions: 0+)
	offset, err := protocol.ReadInt64(r)
	if err != nil {
		return streamsgroupheartbeatrequesttaskendoffset, err
	}
	streamsgroupheartbeatrequesttaskendoffset.Offset = offset

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatrequesttaskendoffset, err
		}
		streamsgroupheartbeatrequesttaskendoffset.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatrequesttaskendoffset, nil
}

//goland:noinspection GoUnhandledErrorResult
func (req *StreamsGroupHeartbeatRequest) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "    -> StreamsGroupHeartbeatRequest:\n")

	if req.GroupId != nil {
		fmt.Fprintf(w, "        GroupId: %v\n", *req.GroupId)
	} else {
		fmt.Fprintf(w, "        GroupId: nil\n")
	}

	if req.MemberId != nil {
		fmt.Fprintf(w, "        MemberId: %v\n", *req.MemberId)
	} else {
		fmt.Fprintf(w, "        MemberId: nil\n")
	}

	fmt.Fprintf(w, "        MemberEpoch: %v\n", req.MemberEpoch)
	fmt.Fprintf(w, "        EndpointInformationEpoch: %v\n", req.EndpointInformationEpoch)

	if req.InstanceId != nil {
		fmt.Fprintf(w, "        InstanceId: %v\n", *req.InstanceId)
	} else {
		fmt.Fprintf(w, "        InstanceId: nil\n")
	}

	if req.RackId != nil {
		fmt.Fprintf(w, "        RackId: %v\n", *req.RackId)
	} else {
		fmt.Fprintf(w, "        RackId: nil\n")
	}

	fmt.Fprintf(w, "        RebalanceTimeoutMs: %v\n", req.RebalanceTimeoutMs)

	fmt.Fprintf(w, "        Topology:\n")
	if req.Topology != nil {
		fmt.Fprintf(w, "%s", req.Topology.PrettyPrint())
	} else {
		fmt.Fprintf(w, "            nil\n")
	}

	if req.ActiveTasks != nil {
		fmt.Fprintf(w, "        ActiveTasks:\n")
		for _, activetasks := range *req.ActiveTasks {
			fmt.Fprintf(w, "%s", activetasks.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        ActiveTasks: nil\n")
	}

	if req.StandbyTasks != nil {
		fmt.Fprintf(w, "        StandbyTasks:\n")
		for _, standbytasks := range *req.StandbyTasks {
			fmt.Fprintf(w, "%s", standbytasks.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        StandbyTasks: nil\n")
	}

	if req.WarmupTasks != nil {
		fmt.Fprintf(w, "        WarmupTasks:\n")
		for _, warmuptasks := range *req.WarmupTasks {
			fmt.Fprintf(w, "%s", warmuptasks.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        WarmupTasks: nil\n")
	}

	if req.ProcessId != nil {
		fmt.Fprintf(w, "        ProcessId: %v\n", *req.ProcessId)
	} else {
		fmt.Fprintf(w, "        ProcessId: nil\n")
	}

	fmt.Fprintf(w, "        UserEndpoint:\n")
	if req.UserEndpoint != nil {
		fmt.Fprintf(w, "%s", req.UserEndpoint.PrettyPrint())
	} else {
		fmt.Fprintf(w, "            nil\n")
	}

	if req.ClientTags != nil {
		fmt.Fprintf(w, "        ClientTags:\n")
		for _, clienttags := range *req.ClientTags {
			fmt.Fprintf(w, "%s", clienttags.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        ClientTags: nil\n")
	}

	if req.TaskOffsets != nil {
		fmt.Fprintf(w, "        TaskOffsets:\n")
		for _, taskoffsets := range *req.TaskOffsets {
			fmt.Fprintf(w, "%s", taskoffsets.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        TaskOffsets: nil\n")
	}

	if req.TaskEndOffsets != nil {
		fmt.Fprintf(w, "        TaskEndOffsets:\n")
		for _, taskendoffsets := range *req.TaskEndOffsets {
			fmt.Fprintf(w, "%s", taskendoffsets.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        TaskEndOffsets: nil\n")
	}

	fmt.Fprintf(w, "        ShutdownApplication: %v\n", req.ShutdownApplication)

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTopology) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "            Epoch: %v\n", value.Epoch)

	if value.Subtopologies != nil {
		fmt.Fprintf(w, "            Subtopologies:\n")
		for _, subtopologies := range *value.Subtopologies {
			fmt.Fprintf(w, "%s", subtopologies.PrettyPrint())
			fmt.Fprintf(w, "                ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "            Subtopologies: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTopologySubtopologie) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "                SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "                SubtopologyId: nil\n")
	}

	if value.SourceTopics != nil {
		fmt.Fprintf(w, "                SourceTopics: %v\n", *value.SourceTopics)
	} else {
		fmt.Fprintf(w, "                SourceTopics: nil\n")
	}

	if value.SourceTopicRegex != nil {
		fmt.Fprintf(w, "                SourceTopicRegex: %v\n", *value.SourceTopicRegex)
	} else {
		fmt.Fprintf(w, "                SourceTopicRegex: nil\n")
	}

	if value.StateChangelogTopics != nil {
		fmt.Fprintf(w, "                StateChangelogTopics:\n")
		for _, statechangelogtopics := range *value.StateChangelogTopics {
			fmt.Fprintf(w, "%s", statechangelogtopics.PrettyPrint())
			fmt.Fprintf(w, "                    ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "                StateChangelogTopics: nil\n")
	}

	if value.RepartitionSinkTopics != nil {
		fmt.Fprintf(w, "                RepartitionSinkTopics: %v\n", *value.RepartitionSinkTopics)
	} else {
		fmt.Fprintf(w, "                RepartitionSinkTopics: nil\n")
	}

	if value.RepartitionSourceTopics != nil {
		fmt.Fprintf(w, "                RepartitionSourceTopics:\n")
		for _, repartitionsourcetopics := range *value.RepartitionSourceTopics {
			fmt.Fprintf(w, "%s", repartitionsourcetopics.PrettyPrint())
			fmt.Fprintf(w, "                    ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "                RepartitionSourceTopics: nil\n")
	}

	if value.CopartitionGroups != nil {
		fmt.Fprintf(w, "                CopartitionGroups:\n")
		for _, copartitiongroups := range *value.CopartitionGroups {
			fmt.Fprintf(w, "%s", copartitiongroups.PrettyPrint())
			fmt.Fprintf(w, "                    ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "                CopartitionGroups: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopic) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Name != nil {
		fmt.Fprintf(w, "                    Name: %v\n", *value.Name)
	} else {
		fmt.Fprintf(w, "                    Name: nil\n")
	}

	fmt.Fprintf(w, "                    Partitions: %v\n", value.Partitions)
	fmt.Fprintf(w, "                    ReplicationFactor: %v\n", value.ReplicationFactor)

	if value.TopicConfigs != nil {
		fmt.Fprintf(w, "                    TopicConfigs:\n")
		for _, topicconfigs := range *value.TopicConfigs {
			fmt.Fprintf(w, "%s", topicconfigs.PrettyPrint())
			fmt.Fprintf(w, "                        ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "                    TopicConfigs: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTopologySubtopologieStateChangelogTopicTopicConfig) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Key != nil {
		fmt.Fprintf(w, "                        Key: %v\n", *value.Key)
	} else {
		fmt.Fprintf(w, "                        Key: nil\n")
	}

	if value.Value != nil {
		fmt.Fprintf(w, "                        Value: %v\n", *value.Value)
	} else {
		fmt.Fprintf(w, "                        Value: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopic) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Name != nil {
		fmt.Fprintf(w, "                    Name: %v\n", *value.Name)
	} else {
		fmt.Fprintf(w, "                    Name: nil\n")
	}

	fmt.Fprintf(w, "                    Partitions: %v\n", value.Partitions)
	fmt.Fprintf(w, "                    ReplicationFactor: %v\n", value.ReplicationFactor)

	if value.TopicConfigs != nil {
		fmt.Fprintf(w, "                    TopicConfigs:\n")
		for _, topicconfigs := range *value.TopicConfigs {
			fmt.Fprintf(w, "%s", topicconfigs.PrettyPrint())
			fmt.Fprintf(w, "                        ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "                    TopicConfigs: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTopologySubtopologieRepartitionSourceTopicTopicConfig) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Key != nil {
		fmt.Fprintf(w, "                        Key: %v\n", *value.Key)
	} else {
		fmt.Fprintf(w, "                        Key: nil\n")
	}

	if value.Value != nil {
		fmt.Fprintf(w, "                        Value: %v\n", *value.Value)
	} else {
		fmt.Fprintf(w, "                        Value: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTopologySubtopologieCopartitionGroup) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SourceTopics != nil {
		fmt.Fprintf(w, "                    SourceTopics: %v\n", *value.SourceTopics)
	} else {
		fmt.Fprintf(w, "                    SourceTopics: nil\n")
	}

	if value.SourceTopicRegex != nil {
		fmt.Fprintf(w, "                    SourceTopicRegex: %v\n", *value.SourceTopicRegex)
	} else {
		fmt.Fprintf(w, "                    SourceTopicRegex: nil\n")
	}

	if value.RepartitionSourceTopics != nil {
		fmt.Fprintf(w, "                    RepartitionSourceTopics: %v\n", *value.RepartitionSourceTopics)
	} else {
		fmt.Fprintf(w, "                    RepartitionSourceTopics: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestActiveTask) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "            SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "            SubtopologyId: nil\n")
	}

	if value.Partitions != nil {
		fmt.Fprintf(w, "            Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "            Partitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestStandbyTask) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "            SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "            SubtopologyId: nil\n")
	}

	if value.Partitions != nil {
		fmt.Fprintf(w, "            Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "            Partitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestWarmupTask) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "            SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "            SubtopologyId: nil\n")
	}

	if value.Partitions != nil {
		fmt.Fprintf(w, "            Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "            Partitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestUserEndpoint) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Host != nil {
		fmt.Fprintf(w, "            Host: %v\n", *value.Host)
	} else {
		fmt.Fprintf(w, "            Host: nil\n")
	}

	fmt.Fprintf(w, "            Port: %v\n", value.Port)

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestClientTag) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Key != nil {
		fmt.Fprintf(w, "            Key: %v\n", *value.Key)
	} else {
		fmt.Fprintf(w, "            Key: nil\n")
	}

	if value.Value != nil {
		fmt.Fprintf(w, "            Value: %v\n", *value.Value)
	} else {
		fmt.Fprintf(w, "            Value: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTaskOffset) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "            SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "            SubtopologyId: nil\n")
	}

	fmt.Fprintf(w, "            Partition: %v\n", value.Partition)
	fmt.Fprintf(w, "            Offset: %v\n", value.Offset)

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatRequestTaskEndOffset) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "            SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "            SubtopologyId: nil\n")
	}

	fmt.Fprintf(w, "            Partition: %v\n", value.Partition)
	fmt.Fprintf(w, "            Offset: %v\n", value.Offset)

	return w.String()
}
