package streamsgroupheartbeat

import (
	"bytes"
	"fmt"
	"github.com/scholzj/go-kafka-protocol/protocol"
	"io"
)

type StreamsGroupHeartbeatResponse struct {
	ApiVersion               int16
	ThrottleTimeMs           int32                                                    // The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. (versions: 0+)
	ErrorCode                int16                                                    // The top-level error code, or 0 if there was no error (versions: 0+)
	ErrorMessage             *string                                                  // The top-level error message, or null if there was no error. (versions: 0+, nullable: 0+)
	MemberId                 *string                                                  // The member id is always generated by the streams consumer. (versions: 0+)
	MemberEpoch              int32                                                    // The member epoch. (versions: 0+)
	HeartbeatIntervalMs      int32                                                    // The heartbeat interval in milliseconds. (versions: 0+)
	AcceptableRecoveryLag    int32                                                    // The maximal lag a warm-up task can have to be considered caught-up. (versions: 0+)
	TaskOffsetIntervalMs     int32                                                    // The interval in which the task changelog offsets on a client are updated on the broker. The offsets are sent with the next heartbeat after this time has passed. (versions: 0+)
	Status                   *[]StreamsGroupHeartbeatResponseStatu                    // Indicate zero or more status for the group. (versions: 0+, nullable: 0+)
	ActiveTasks              *[]StreamsGroupHeartbeatResponseActiveTask               // Assigned active tasks for this client. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	StandbyTasks             *[]StreamsGroupHeartbeatResponseStandbyTask              // Assigned standby tasks for this client. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	WarmupTasks              *[]StreamsGroupHeartbeatResponseWarmupTask               // Assigned warm-up tasks for this client. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	EndpointInformationEpoch int32                                                    // The endpoint epoch set in the response (versions: 0+)
	PartitionsByUserEndpoint *[]StreamsGroupHeartbeatResponsePartitionsByUserEndpoint // Global assignment information used for IQ. Null if unchanged since last heartbeat. (versions: 0+, nullable: 0+)
	rawTaggedFields          *[]protocol.TaggedField
}

type StreamsGroupHeartbeatResponseStatu struct {
	StatusCode      int8    // A code to indicate that a particular status is active for the group membership (versions: 0+)
	StatusDetail    *string // A string representation of the status. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatResponseActiveTask struct {
	SubtopologyId   *string  // The subtopology identifier. (versions: 0+)
	Partitions      *[]int32 // The partitions of the input topics processed by this member. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatResponseStandbyTask struct {
	SubtopologyId   *string  // The subtopology identifier. (versions: 0+)
	Partitions      *[]int32 // The partitions of the input topics processed by this member. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatResponseWarmupTask struct {
	SubtopologyId   *string  // The subtopology identifier. (versions: 0+)
	Partitions      *[]int32 // The partitions of the input topics processed by this member. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatResponsePartitionsByUserEndpoint struct {
	UserEndpoint      *StreamsGroupHeartbeatResponsePartitionsByUserEndpointUserEndpoint       // User-defined endpoint to connect to the node (versions: 0+)
	ActivePartitions  *[]StreamsGroupHeartbeatResponsePartitionsByUserEndpointActivePartition  // All topic partitions materialized by active tasks on the node (versions: 0+)
	StandbyPartitions *[]StreamsGroupHeartbeatResponsePartitionsByUserEndpointStandbyPartition // All topic partitions materialized by standby tasks on the node (versions: 0+)
	rawTaggedFields   *[]protocol.TaggedField
}

type StreamsGroupHeartbeatResponsePartitionsByUserEndpointUserEndpoint struct {
	Host            *string // host of the endpoint (versions: 0+)
	Port            uint16  // port of the endpoint (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatResponsePartitionsByUserEndpointActivePartition struct {
	Topic           *string  // topic name (versions: 0+)
	Partitions      *[]int32 // partitions (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type StreamsGroupHeartbeatResponsePartitionsByUserEndpointStandbyPartition struct {
	Topic           *string  // topic name (versions: 0+)
	Partitions      *[]int32 // partitions (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

func isResponseFlexible(apiVersion int16) bool {
	return apiVersion >= 0
}

func (res *StreamsGroupHeartbeatResponse) Write(w io.Writer) error {
	// ThrottleTimeMs (versions: 0+)
	if err := protocol.WriteInt32(w, res.ThrottleTimeMs); err != nil {
		return err
	}

	// ErrorCode (versions: 0+)
	if err := protocol.WriteInt16(w, res.ErrorCode); err != nil {
		return err
	}

	// ErrorMessage (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, res.ErrorMessage); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, res.ErrorMessage); err != nil {
			return err
		}
	}

	// MemberId (versions: 0+)
	if res.MemberId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponse.MemberId must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteCompactString(w, *res.MemberId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *res.MemberId); err != nil {
			return err
		}
	}

	// MemberEpoch (versions: 0+)
	if err := protocol.WriteInt32(w, res.MemberEpoch); err != nil {
		return err
	}

	// HeartbeatIntervalMs (versions: 0+)
	if err := protocol.WriteInt32(w, res.HeartbeatIntervalMs); err != nil {
		return err
	}

	// AcceptableRecoveryLag (versions: 0+)
	if err := protocol.WriteInt32(w, res.AcceptableRecoveryLag); err != nil {
		return err
	}

	// TaskOffsetIntervalMs (versions: 0+)
	if err := protocol.WriteInt32(w, res.TaskOffsetIntervalMs); err != nil {
		return err
	}

	// Status (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, res.statusEncoder, res.Status); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, res.statusEncoder, res.Status); err != nil {
			return err
		}
	}

	// ActiveTasks (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, res.activeTasksEncoder, res.ActiveTasks); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, res.activeTasksEncoder, res.ActiveTasks); err != nil {
			return err
		}
	}

	// StandbyTasks (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, res.standbyTasksEncoder, res.StandbyTasks); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, res.standbyTasksEncoder, res.StandbyTasks); err != nil {
			return err
		}
	}

	// WarmupTasks (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, res.warmupTasksEncoder, res.WarmupTasks); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, res.warmupTasksEncoder, res.WarmupTasks); err != nil {
			return err
		}
	}

	// EndpointInformationEpoch (versions: 0+)
	if err := protocol.WriteInt32(w, res.EndpointInformationEpoch); err != nil {
		return err
	}

	// PartitionsByUserEndpoint (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, res.partitionsByUserEndpointEncoder, res.PartitionsByUserEndpoint); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, res.partitionsByUserEndpointEncoder, res.PartitionsByUserEndpoint); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if res.rawTaggedFields != nil {
			rawTaggedFields = *res.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

// TODO: pass version and bytes only
func (res *StreamsGroupHeartbeatResponse) Read(response *protocol.Response) error {
	if response == nil || response.Body == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponse.Read: response or its body is nil")
	}

	r := bytes.NewBuffer(response.Body.Bytes())
	res.ApiVersion = response.ApiVersion

	// ThrottleTimeMs (versions: 0+)
	throttletimems, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.ThrottleTimeMs = throttletimems

	// ErrorCode (versions: 0+)
	errorcode, err := protocol.ReadInt16(r)
	if err != nil {
		return err
	}
	res.ErrorCode = errorcode

	// ErrorMessage (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		errormessage, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		res.ErrorMessage = errormessage
	} else {
		errormessage, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		res.ErrorMessage = errormessage
	}

	// MemberId (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		memberid, err := protocol.ReadCompactString(r)
		if err != nil {
			return err
		}
		res.MemberId = &memberid
	} else {
		memberid, err := protocol.ReadString(r)
		if err != nil {
			return err
		}
		res.MemberId = &memberid
	}

	// MemberEpoch (versions: 0+)
	memberepoch, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.MemberEpoch = memberepoch

	// HeartbeatIntervalMs (versions: 0+)
	heartbeatintervalms, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.HeartbeatIntervalMs = heartbeatintervalms

	// AcceptableRecoveryLag (versions: 0+)
	acceptablerecoverylag, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.AcceptableRecoveryLag = acceptablerecoverylag

	// TaskOffsetIntervalMs (versions: 0+)
	taskoffsetintervalms, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.TaskOffsetIntervalMs = taskoffsetintervalms

	// Status (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		status, err := protocol.ReadNullableCompactArray(r, res.statusDecoder)
		if err != nil {
			return err
		}
		res.Status = status
	} else {
		status, err := protocol.ReadNullableArray(r, res.statusDecoder)
		if err != nil {
			return err
		}
		res.Status = status
	}

	// ActiveTasks (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		activetasks, err := protocol.ReadNullableCompactArray(r, res.activeTasksDecoder)
		if err != nil {
			return err
		}
		res.ActiveTasks = activetasks
	} else {
		activetasks, err := protocol.ReadNullableArray(r, res.activeTasksDecoder)
		if err != nil {
			return err
		}
		res.ActiveTasks = activetasks
	}

	// StandbyTasks (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		standbytasks, err := protocol.ReadNullableCompactArray(r, res.standbyTasksDecoder)
		if err != nil {
			return err
		}
		res.StandbyTasks = standbytasks
	} else {
		standbytasks, err := protocol.ReadNullableArray(r, res.standbyTasksDecoder)
		if err != nil {
			return err
		}
		res.StandbyTasks = standbytasks
	}

	// WarmupTasks (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		warmuptasks, err := protocol.ReadNullableCompactArray(r, res.warmupTasksDecoder)
		if err != nil {
			return err
		}
		res.WarmupTasks = warmuptasks
	} else {
		warmuptasks, err := protocol.ReadNullableArray(r, res.warmupTasksDecoder)
		if err != nil {
			return err
		}
		res.WarmupTasks = warmuptasks
	}

	// EndpointInformationEpoch (versions: 0+)
	endpointinformationepoch, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.EndpointInformationEpoch = endpointinformationepoch

	// PartitionsByUserEndpoint (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		partitionsbyuserendpoint, err := protocol.ReadNullableCompactArray(r, res.partitionsByUserEndpointDecoder)
		if err != nil {
			return err
		}
		res.PartitionsByUserEndpoint = partitionsbyuserendpoint
	} else {
		partitionsbyuserendpoint, err := protocol.ReadNullableArray(r, res.partitionsByUserEndpointDecoder)
		if err != nil {
			return err
		}
		res.PartitionsByUserEndpoint = partitionsbyuserendpoint
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return err
		}
		res.rawTaggedFields = &rawTaggedFields
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) statusEncoder(w io.Writer, value StreamsGroupHeartbeatResponseStatu) error {
	// StatusCode (versions: 0+)
	if err := protocol.WriteInt8(w, value.StatusCode); err != nil {
		return err
	}

	// StatusDetail (versions: 0+)
	if value.StatusDetail == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponseStatu.StatusDetail must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.StatusDetail); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.StatusDetail); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) statusDecoder(r io.Reader) (StreamsGroupHeartbeatResponseStatu, error) {
	streamsgroupheartbeatresponsestatu := StreamsGroupHeartbeatResponseStatu{}

	// StatusCode (versions: 0+)
	statuscode, err := protocol.ReadInt8(r)
	if err != nil {
		return streamsgroupheartbeatresponsestatu, err
	}
	streamsgroupheartbeatresponsestatu.StatusCode = statuscode

	// StatusDetail (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		statusdetail, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatresponsestatu, err
		}
		streamsgroupheartbeatresponsestatu.StatusDetail = &statusdetail
	} else {
		statusdetail, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatresponsestatu, err
		}
		streamsgroupheartbeatresponsestatu.StatusDetail = &statusdetail
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatresponsestatu, err
		}
		streamsgroupheartbeatresponsestatu.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatresponsestatu, nil
}

func (res *StreamsGroupHeartbeatResponse) activeTasksEncoder(w io.Writer, value StreamsGroupHeartbeatResponseActiveTask) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponseActiveTask.SubtopologyId must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponseActiveTask.Partitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) activeTasksDecoder(r io.Reader) (StreamsGroupHeartbeatResponseActiveTask, error) {
	streamsgroupheartbeatresponseactivetask := StreamsGroupHeartbeatResponseActiveTask{}

	// SubtopologyId (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatresponseactivetask, err
		}
		streamsgroupheartbeatresponseactivetask.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatresponseactivetask, err
		}
		streamsgroupheartbeatresponseactivetask.SubtopologyId = &subtopologyid
	}

	// Partitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponseactivetask, err
		}
		streamsgroupheartbeatresponseactivetask.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponseactivetask, err
		}
		streamsgroupheartbeatresponseactivetask.Partitions = &partitions
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatresponseactivetask, err
		}
		streamsgroupheartbeatresponseactivetask.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatresponseactivetask, nil
}

func (res *StreamsGroupHeartbeatResponse) standbyTasksEncoder(w io.Writer, value StreamsGroupHeartbeatResponseStandbyTask) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponseStandbyTask.SubtopologyId must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponseStandbyTask.Partitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) standbyTasksDecoder(r io.Reader) (StreamsGroupHeartbeatResponseStandbyTask, error) {
	streamsgroupheartbeatresponsestandbytask := StreamsGroupHeartbeatResponseStandbyTask{}

	// SubtopologyId (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatresponsestandbytask, err
		}
		streamsgroupheartbeatresponsestandbytask.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatresponsestandbytask, err
		}
		streamsgroupheartbeatresponsestandbytask.SubtopologyId = &subtopologyid
	}

	// Partitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponsestandbytask, err
		}
		streamsgroupheartbeatresponsestandbytask.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponsestandbytask, err
		}
		streamsgroupheartbeatresponsestandbytask.Partitions = &partitions
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatresponsestandbytask, err
		}
		streamsgroupheartbeatresponsestandbytask.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatresponsestandbytask, nil
}

func (res *StreamsGroupHeartbeatResponse) warmupTasksEncoder(w io.Writer, value StreamsGroupHeartbeatResponseWarmupTask) error {
	// SubtopologyId (versions: 0+)
	if value.SubtopologyId == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponseWarmupTask.SubtopologyId must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.SubtopologyId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.SubtopologyId); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponseWarmupTask.Partitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) warmupTasksDecoder(r io.Reader) (StreamsGroupHeartbeatResponseWarmupTask, error) {
	streamsgroupheartbeatresponsewarmuptask := StreamsGroupHeartbeatResponseWarmupTask{}

	// SubtopologyId (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		subtopologyid, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatresponsewarmuptask, err
		}
		streamsgroupheartbeatresponsewarmuptask.SubtopologyId = &subtopologyid
	} else {
		subtopologyid, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatresponsewarmuptask, err
		}
		streamsgroupheartbeatresponsewarmuptask.SubtopologyId = &subtopologyid
	}

	// Partitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponsewarmuptask, err
		}
		streamsgroupheartbeatresponsewarmuptask.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponsewarmuptask, err
		}
		streamsgroupheartbeatresponsewarmuptask.Partitions = &partitions
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatresponsewarmuptask, err
		}
		streamsgroupheartbeatresponsewarmuptask.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatresponsewarmuptask, nil
}

func (res *StreamsGroupHeartbeatResponse) partitionsByUserEndpointEncoder(w io.Writer, value StreamsGroupHeartbeatResponsePartitionsByUserEndpoint) error {
	// UserEndpoint (versions: 0+)
	if value.UserEndpoint == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponsePartitionsByUserEndpoint.UserEndpoint must not be nil in version %d", res.ApiVersion)
	}
	if err := res.userEndpointEncoder(w, *value.UserEndpoint); err != nil {
		return err
	}

	// ActivePartitions (versions: 0+)
	if value.ActivePartitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponsePartitionsByUserEndpoint.ActivePartitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, res.activePartitionsEncoder, value.ActivePartitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, res.activePartitionsEncoder, *value.ActivePartitions); err != nil {
			return err
		}
	}

	// StandbyPartitions (versions: 0+)
	if value.StandbyPartitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponsePartitionsByUserEndpoint.StandbyPartitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, res.standbyPartitionsEncoder, value.StandbyPartitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, res.standbyPartitionsEncoder, *value.StandbyPartitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) partitionsByUserEndpointDecoder(r io.Reader) (StreamsGroupHeartbeatResponsePartitionsByUserEndpoint, error) {
	streamsgroupheartbeatresponsepartitionsbyuserendpoint := StreamsGroupHeartbeatResponsePartitionsByUserEndpoint{}

	// UserEndpoint (versions: 0+)
	userendpoint, err := res.userEndpointDecoder(r)
	if err != nil {
		return streamsgroupheartbeatresponsepartitionsbyuserendpoint, err
	}
	streamsgroupheartbeatresponsepartitionsbyuserendpoint.UserEndpoint = &userendpoint

	// ActivePartitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		activepartitions, err := protocol.ReadNullableCompactArray(r, res.activePartitionsDecoder)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpoint, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpoint.ActivePartitions = activepartitions
	} else {
		activepartitions, err := protocol.ReadArray(r, res.activePartitionsDecoder)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpoint, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpoint.ActivePartitions = &activepartitions
	}

	// StandbyPartitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		standbypartitions, err := protocol.ReadNullableCompactArray(r, res.standbyPartitionsDecoder)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpoint, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpoint.StandbyPartitions = standbypartitions
	} else {
		standbypartitions, err := protocol.ReadArray(r, res.standbyPartitionsDecoder)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpoint, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpoint.StandbyPartitions = &standbypartitions
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpoint, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpoint.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatresponsepartitionsbyuserendpoint, nil
}

func (res *StreamsGroupHeartbeatResponse) userEndpointEncoder(w io.Writer, value StreamsGroupHeartbeatResponsePartitionsByUserEndpointUserEndpoint) error {
	// Host (versions: 0+)
	if value.Host == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponsePartitionsByUserEndpointUserEndpoint.Host must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Host); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Host); err != nil {
			return err
		}
	}

	// Port (versions: 0+)
	if err := protocol.WriteUint16(w, value.Port); err != nil {
		return err
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) userEndpointDecoder(r io.Reader) (StreamsGroupHeartbeatResponsePartitionsByUserEndpointUserEndpoint, error) {
	streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint := StreamsGroupHeartbeatResponsePartitionsByUserEndpointUserEndpoint{}

	// Host (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		host, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint.Host = &host
	} else {
		host, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint.Host = &host
	}

	// Port (versions: 0+)
	port, err := protocol.ReadUInt16(r)
	if err != nil {
		return streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint, err
	}
	streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint.Port = port

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatresponsepartitionsbyuserendpointuserendpoint, nil
}

func (res *StreamsGroupHeartbeatResponse) activePartitionsEncoder(w io.Writer, value StreamsGroupHeartbeatResponsePartitionsByUserEndpointActivePartition) error {
	// Topic (versions: 0+)
	if value.Topic == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponsePartitionsByUserEndpointActivePartition.Topic must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Topic); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Topic); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponsePartitionsByUserEndpointActivePartition.Partitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) activePartitionsDecoder(r io.Reader) (StreamsGroupHeartbeatResponsePartitionsByUserEndpointActivePartition, error) {
	streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition := StreamsGroupHeartbeatResponsePartitionsByUserEndpointActivePartition{}

	// Topic (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		topic, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition.Topic = &topic
	} else {
		topic, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition.Topic = &topic
	}

	// Partitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition.Partitions = &partitions
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatresponsepartitionsbyuserendpointactivepartition, nil
}

func (res *StreamsGroupHeartbeatResponse) standbyPartitionsEncoder(w io.Writer, value StreamsGroupHeartbeatResponsePartitionsByUserEndpointStandbyPartition) error {
	// Topic (versions: 0+)
	if value.Topic == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponsePartitionsByUserEndpointStandbyPartition.Topic must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteCompactString(w, *value.Topic); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *value.Topic); err != nil {
			return err
		}
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("StreamsGroupHeartbeatResponsePartitionsByUserEndpointStandbyPartition.Partitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *StreamsGroupHeartbeatResponse) standbyPartitionsDecoder(r io.Reader) (StreamsGroupHeartbeatResponsePartitionsByUserEndpointStandbyPartition, error) {
	streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition := StreamsGroupHeartbeatResponsePartitionsByUserEndpointStandbyPartition{}

	// Topic (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		topic, err := protocol.ReadCompactString(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition.Topic = &topic
	} else {
		topic, err := protocol.ReadString(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition.Topic = &topic
	}

	// Partitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition.Partitions = &partitions
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition, err
		}
		streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition.rawTaggedFields = &rawTaggedFields
	}

	return streamsgroupheartbeatresponsepartitionsbyuserendpointstandbypartition, nil
}

//goland:noinspection GoUnhandledErrorResult
func (res *StreamsGroupHeartbeatResponse) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "    <- StreamsGroupHeartbeatResponse:\n")
	fmt.Fprintf(w, "        ThrottleTimeMs: %v\n", res.ThrottleTimeMs)
	fmt.Fprintf(w, "        ErrorCode: %v\n", res.ErrorCode)

	if res.ErrorMessage != nil {
		fmt.Fprintf(w, "        ErrorMessage: %v\n", *res.ErrorMessage)
	} else {
		fmt.Fprintf(w, "        ErrorMessage: nil\n")
	}

	if res.MemberId != nil {
		fmt.Fprintf(w, "        MemberId: %v\n", *res.MemberId)
	} else {
		fmt.Fprintf(w, "        MemberId: nil\n")
	}

	fmt.Fprintf(w, "        MemberEpoch: %v\n", res.MemberEpoch)
	fmt.Fprintf(w, "        HeartbeatIntervalMs: %v\n", res.HeartbeatIntervalMs)
	fmt.Fprintf(w, "        AcceptableRecoveryLag: %v\n", res.AcceptableRecoveryLag)
	fmt.Fprintf(w, "        TaskOffsetIntervalMs: %v\n", res.TaskOffsetIntervalMs)

	if res.Status != nil {
		fmt.Fprintf(w, "        Status:\n")
		for _, status := range *res.Status {
			fmt.Fprintf(w, "%s", status.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        Status: nil\n")
	}

	if res.ActiveTasks != nil {
		fmt.Fprintf(w, "        ActiveTasks:\n")
		for _, activetasks := range *res.ActiveTasks {
			fmt.Fprintf(w, "%s", activetasks.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        ActiveTasks: nil\n")
	}

	if res.StandbyTasks != nil {
		fmt.Fprintf(w, "        StandbyTasks:\n")
		for _, standbytasks := range *res.StandbyTasks {
			fmt.Fprintf(w, "%s", standbytasks.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        StandbyTasks: nil\n")
	}

	if res.WarmupTasks != nil {
		fmt.Fprintf(w, "        WarmupTasks:\n")
		for _, warmuptasks := range *res.WarmupTasks {
			fmt.Fprintf(w, "%s", warmuptasks.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        WarmupTasks: nil\n")
	}

	fmt.Fprintf(w, "        EndpointInformationEpoch: %v\n", res.EndpointInformationEpoch)

	if res.PartitionsByUserEndpoint != nil {
		fmt.Fprintf(w, "        PartitionsByUserEndpoint:\n")
		for _, partitionsbyuserendpoint := range *res.PartitionsByUserEndpoint {
			fmt.Fprintf(w, "%s", partitionsbyuserendpoint.PrettyPrint())
			fmt.Fprintf(w, "            ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "        PartitionsByUserEndpoint: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatResponseStatu) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "            StatusCode: %v\n", value.StatusCode)

	if value.StatusDetail != nil {
		fmt.Fprintf(w, "            StatusDetail: %v\n", *value.StatusDetail)
	} else {
		fmt.Fprintf(w, "            StatusDetail: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatResponseActiveTask) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "            SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "            SubtopologyId: nil\n")
	}

	if value.Partitions != nil {
		fmt.Fprintf(w, "            Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "            Partitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatResponseStandbyTask) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "            SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "            SubtopologyId: nil\n")
	}

	if value.Partitions != nil {
		fmt.Fprintf(w, "            Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "            Partitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatResponseWarmupTask) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.SubtopologyId != nil {
		fmt.Fprintf(w, "            SubtopologyId: %v\n", *value.SubtopologyId)
	} else {
		fmt.Fprintf(w, "            SubtopologyId: nil\n")
	}

	if value.Partitions != nil {
		fmt.Fprintf(w, "            Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "            Partitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatResponsePartitionsByUserEndpoint) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "            UserEndpoint:\n")
	if value.UserEndpoint != nil {
		fmt.Fprintf(w, "%s", value.UserEndpoint.PrettyPrint())
	} else {
		fmt.Fprintf(w, "                nil\n")
	}

	if value.ActivePartitions != nil {
		fmt.Fprintf(w, "            ActivePartitions:\n")
		for _, activepartitions := range *value.ActivePartitions {
			fmt.Fprintf(w, "%s", activepartitions.PrettyPrint())
			fmt.Fprintf(w, "                ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "            ActivePartitions: nil\n")
	}

	if value.StandbyPartitions != nil {
		fmt.Fprintf(w, "            StandbyPartitions:\n")
		for _, standbypartitions := range *value.StandbyPartitions {
			fmt.Fprintf(w, "%s", standbypartitions.PrettyPrint())
			fmt.Fprintf(w, "                ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "            StandbyPartitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatResponsePartitionsByUserEndpointUserEndpoint) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Host != nil {
		fmt.Fprintf(w, "                Host: %v\n", *value.Host)
	} else {
		fmt.Fprintf(w, "                Host: nil\n")
	}

	fmt.Fprintf(w, "                Port: %v\n", value.Port)

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatResponsePartitionsByUserEndpointActivePartition) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Topic != nil {
		fmt.Fprintf(w, "                Topic: %v\n", *value.Topic)
	} else {
		fmt.Fprintf(w, "                Topic: nil\n")
	}

	if value.Partitions != nil {
		fmt.Fprintf(w, "                Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "                Partitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *StreamsGroupHeartbeatResponsePartitionsByUserEndpointStandbyPartition) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.Topic != nil {
		fmt.Fprintf(w, "                Topic: %v\n", *value.Topic)
	} else {
		fmt.Fprintf(w, "                Topic: nil\n")
	}

	if value.Partitions != nil {
		fmt.Fprintf(w, "                Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "                Partitions: nil\n")
	}

	return w.String()
}
