package streamsgroupheartbeat

import (
	"bytes"
	"errors"
	"io"

	"github.com/scholzj/go-kafka-protocol/protocol"
)

const (
	StreamsGroupHeartbeatResponseApiKey        = 88
	StreamsGroupHeartbeatResponseHeaderVersion = 1
)

// StreamsGroupHeartbeatResponse represents a response message.
type StreamsGroupHeartbeatResponse struct {
	// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
	ThrottleTimeMs int32 `json:"throttletimems" versions:"0-999"`
	// The top-level error code, or 0 if there was no error
	ErrorCode int16 `json:"errorcode" versions:"0-999"`
	// The top-level error message, or null if there was no error.
	ErrorMessage *string `json:"errormessage" versions:"0-999"`
	// The member id is always generated by the streams consumer.
	MemberId string `json:"memberid" versions:"0-999"`
	// The member epoch.
	MemberEpoch int32 `json:"memberepoch" versions:"0-999"`
	// The heartbeat interval in milliseconds.
	HeartbeatIntervalMs int32 `json:"heartbeatintervalms" versions:"0-999"`
	// The maximal lag a warm-up task can have to be considered caught-up.
	AcceptableRecoveryLag int32 `json:"acceptablerecoverylag" versions:"0-999"`
	// The interval in which the task changelog offsets on a client are updated on the broker. The offsets are sent with the next heartbeat after this time has passed.
	TaskOffsetIntervalMs int32 `json:"taskoffsetintervalms" versions:"0-999"`
	// Indicate zero or more status for the group.
	Status []Status `json:"status" versions:"0-999"`
	// Assigned active tasks for this client. Null if unchanged since last heartbeat.
	ActiveTasks []TaskIds `json:"activetasks" versions:"0-999"`
	// Assigned standby tasks for this client. Null if unchanged since last heartbeat.
	StandbyTasks []TaskIds `json:"standbytasks" versions:"0-999"`
	// Assigned warm-up tasks for this client. Null if unchanged since last heartbeat.
	WarmupTasks []TaskIds `json:"warmuptasks" versions:"0-999"`
	// The endpoint epoch set in the response
	EndpointInformationEpoch int32 `json:"endpointinformationepoch" versions:"0-999"`
	// Global assignment information used for IQ. Null if unchanged since last heartbeat.
	PartitionsByUserEndpoint []StreamsGroupHeartbeatResponseEndpointToPartitions `json:"partitionsbyuserendpoint" versions:"0-999"`
}

// Encode encodes a StreamsGroupHeartbeatResponse to a byte slice for the given version.
func (m *StreamsGroupHeartbeatResponse) Encode(version int16) ([]byte, error) {
	var buf bytes.Buffer
	if err := m.Write(&buf, version); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Decode decodes a StreamsGroupHeartbeatResponse from a byte slice for the given version.
func (m *StreamsGroupHeartbeatResponse) Decode(data []byte, version int16) error {
	r := bytes.NewReader(data)
	return m.Read(r, version)
}

// Write writes a StreamsGroupHeartbeatResponse to an io.Writer for the given version.
func (m *StreamsGroupHeartbeatResponse) Write(w io.Writer, version int16) error {
	if version < 0 || version > 0 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// ThrottleTimeMs
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.ThrottleTimeMs); err != nil {
			return err
		}
	}
	// ErrorCode
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt16(w, m.ErrorCode); err != nil {
			return err
		}
	}
	// ErrorMessage
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.ErrorMessage); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.ErrorMessage); err != nil {
				return err
			}
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactString(w, m.MemberId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteString(w, m.MemberId); err != nil {
				return err
			}
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.MemberEpoch); err != nil {
			return err
		}
	}
	// HeartbeatIntervalMs
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.HeartbeatIntervalMs); err != nil {
			return err
		}
	}
	// AcceptableRecoveryLag
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.AcceptableRecoveryLag); err != nil {
			return err
		}
	}
	// TaskOffsetIntervalMs
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.TaskOffsetIntervalMs); err != nil {
			return err
		}
	}
	// Status
	if version >= 0 && version <= 999 {
		if m.Status == nil {
			if isFlexible {
				if err := protocol.WriteVaruint32(w, 0); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, -1); err != nil {
					return err
				}
			}
		} else {
			if isFlexible {
				length := uint32(len(m.Status) + 1)
				if err := protocol.WriteVaruint32(w, length); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, int32(len(m.Status))); err != nil {
					return err
				}
			}
			for i := range m.Status {
				// StatusCode
				if version >= 0 && version <= 999 {
					if err := protocol.WriteInt8(w, m.Status[i].StatusCode); err != nil {
						return err
					}
				}
				// StatusDetail
				if version >= 0 && version <= 999 {
					if isFlexible {
						if err := protocol.WriteCompactString(w, m.Status[i].StatusDetail); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteString(w, m.Status[i].StatusDetail); err != nil {
							return err
						}
					}
				}
			}
		}
	}
	// ActiveTasks
	if version >= 0 && version <= 999 {
		if m.ActiveTasks == nil {
			if isFlexible {
				if err := protocol.WriteVaruint32(w, 0); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, -1); err != nil {
					return err
				}
			}
		} else {
			if isFlexible {
				length := uint32(len(m.ActiveTasks) + 1)
				if err := protocol.WriteVaruint32(w, length); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, int32(len(m.ActiveTasks))); err != nil {
					return err
				}
			}
			for i := range m.ActiveTasks {
				// SubtopologyId
				if version >= 0 && version <= 999 {
					if isFlexible {
						if err := protocol.WriteCompactString(w, m.ActiveTasks[i].SubtopologyId); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteString(w, m.ActiveTasks[i].SubtopologyId); err != nil {
							return err
						}
					}
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						length := uint32(len(m.ActiveTasks[i].Partitions) + 1)
						if err := protocol.WriteVaruint32(w, length); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteInt32(w, int32(len(m.ActiveTasks[i].Partitions))); err != nil {
							return err
						}
					}
					for i := range m.ActiveTasks[i].Partitions {
						if err := protocol.WriteInt32(w, m.ActiveTasks[i].Partitions[i]); err != nil {
							return err
						}
						_ = i
					}
				}
			}
		}
	}
	// StandbyTasks
	if version >= 0 && version <= 999 {
		if m.StandbyTasks == nil {
			if isFlexible {
				if err := protocol.WriteVaruint32(w, 0); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, -1); err != nil {
					return err
				}
			}
		} else {
			if isFlexible {
				length := uint32(len(m.StandbyTasks) + 1)
				if err := protocol.WriteVaruint32(w, length); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, int32(len(m.StandbyTasks))); err != nil {
					return err
				}
			}
			for i := range m.StandbyTasks {
				// SubtopologyId
				if version >= 0 && version <= 999 {
					if isFlexible {
						if err := protocol.WriteCompactString(w, m.StandbyTasks[i].SubtopologyId); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteString(w, m.StandbyTasks[i].SubtopologyId); err != nil {
							return err
						}
					}
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						length := uint32(len(m.StandbyTasks[i].Partitions) + 1)
						if err := protocol.WriteVaruint32(w, length); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteInt32(w, int32(len(m.StandbyTasks[i].Partitions))); err != nil {
							return err
						}
					}
					for i := range m.StandbyTasks[i].Partitions {
						if err := protocol.WriteInt32(w, m.StandbyTasks[i].Partitions[i]); err != nil {
							return err
						}
						_ = i
					}
				}
			}
		}
	}
	// WarmupTasks
	if version >= 0 && version <= 999 {
		if m.WarmupTasks == nil {
			if isFlexible {
				if err := protocol.WriteVaruint32(w, 0); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, -1); err != nil {
					return err
				}
			}
		} else {
			if isFlexible {
				length := uint32(len(m.WarmupTasks) + 1)
				if err := protocol.WriteVaruint32(w, length); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, int32(len(m.WarmupTasks))); err != nil {
					return err
				}
			}
			for i := range m.WarmupTasks {
				// SubtopologyId
				if version >= 0 && version <= 999 {
					if isFlexible {
						if err := protocol.WriteCompactString(w, m.WarmupTasks[i].SubtopologyId); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteString(w, m.WarmupTasks[i].SubtopologyId); err != nil {
							return err
						}
					}
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						length := uint32(len(m.WarmupTasks[i].Partitions) + 1)
						if err := protocol.WriteVaruint32(w, length); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteInt32(w, int32(len(m.WarmupTasks[i].Partitions))); err != nil {
							return err
						}
					}
					for i := range m.WarmupTasks[i].Partitions {
						if err := protocol.WriteInt32(w, m.WarmupTasks[i].Partitions[i]); err != nil {
							return err
						}
						_ = i
					}
				}
			}
		}
	}
	// EndpointInformationEpoch
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.EndpointInformationEpoch); err != nil {
			return err
		}
	}
	// PartitionsByUserEndpoint
	if version >= 0 && version <= 999 {
		if m.PartitionsByUserEndpoint == nil {
			if isFlexible {
				if err := protocol.WriteVaruint32(w, 0); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, -1); err != nil {
					return err
				}
			}
		} else {
			if isFlexible {
				length := uint32(len(m.PartitionsByUserEndpoint) + 1)
				if err := protocol.WriteVaruint32(w, length); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, int32(len(m.PartitionsByUserEndpoint))); err != nil {
					return err
				}
			}
			for i := range m.PartitionsByUserEndpoint {
				// UserEndpoint
				if version >= 0 && version <= 999 {
				}
				// ActivePartitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						length := uint32(len(m.PartitionsByUserEndpoint[i].ActivePartitions) + 1)
						if err := protocol.WriteVaruint32(w, length); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteInt32(w, int32(len(m.PartitionsByUserEndpoint[i].ActivePartitions))); err != nil {
							return err
						}
					}
					for i := range m.PartitionsByUserEndpoint[i].ActivePartitions {
						// Topic
						if version >= 0 && version <= 999 {
							if isFlexible {
								if err := protocol.WriteCompactString(w, m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic); err != nil {
									return err
								}
							} else {
								if err := protocol.WriteString(w, m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic); err != nil {
									return err
								}
							}
						}
						// Partitions
						if version >= 0 && version <= 999 {
							if isFlexible {
								length := uint32(len(m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions) + 1)
								if err := protocol.WriteVaruint32(w, length); err != nil {
									return err
								}
							} else {
								if err := protocol.WriteInt32(w, int32(len(m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions))); err != nil {
									return err
								}
							}
							for i := range m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions {
								if err := protocol.WriteInt32(w, m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i]); err != nil {
									return err
								}
								_ = i
							}
						}
					}
				}
				// StandbyPartitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						length := uint32(len(m.PartitionsByUserEndpoint[i].StandbyPartitions) + 1)
						if err := protocol.WriteVaruint32(w, length); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteInt32(w, int32(len(m.PartitionsByUserEndpoint[i].StandbyPartitions))); err != nil {
							return err
						}
					}
					for i := range m.PartitionsByUserEndpoint[i].StandbyPartitions {
						// Topic
						if version >= 0 && version <= 999 {
							if isFlexible {
								if err := protocol.WriteCompactString(w, m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic); err != nil {
									return err
								}
							} else {
								if err := protocol.WriteString(w, m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic); err != nil {
									return err
								}
							}
						}
						// Partitions
						if version >= 0 && version <= 999 {
							if isFlexible {
								length := uint32(len(m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions) + 1)
								if err := protocol.WriteVaruint32(w, length); err != nil {
									return err
								}
							} else {
								if err := protocol.WriteInt32(w, int32(len(m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions))); err != nil {
									return err
								}
							}
							for i := range m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions {
								if err := protocol.WriteInt32(w, m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i]); err != nil {
									return err
								}
								_ = i
							}
						}
					}
				}
			}
		}
	}
	// Write tagged fields if flexible
	if isFlexible {
		if err := m.writeTaggedFields(w, version); err != nil {
			return err
		}
	}
	return nil
}

// Read reads a StreamsGroupHeartbeatResponse from an io.Reader for the given version.
func (m *StreamsGroupHeartbeatResponse) Read(r io.Reader, version int16) error {
	if version < 0 || version > 0 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// ThrottleTimeMs
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = val
	}
	// ErrorCode
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt16(r)
		if err != nil {
			return err
		}
		m.ErrorCode = val
	}
	// ErrorMessage
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.ErrorMessage = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.ErrorMessage = val
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		} else {
			val, err := protocol.ReadString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.MemberEpoch = val
	}
	// HeartbeatIntervalMs
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.HeartbeatIntervalMs = val
	}
	// AcceptableRecoveryLag
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.AcceptableRecoveryLag = val
	}
	// TaskOffsetIntervalMs
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.TaskOffsetIntervalMs = val
	}
	// Status
	if version >= 0 && version <= 999 {
		var length int32
		if isFlexible {
			var lengthUint uint32
			lengthUint, err := protocol.ReadVaruint32(r)
			if err != nil {
				return err
			}
			if lengthUint == 0 {
				m.Status = nil
			} else {
				if lengthUint < 1 {
					return errors.New("invalid compact array length")
				}
				length = int32(lengthUint - 1)
				m.Status = make([]Status, length)
				for i := int32(0); i < length; i++ {
					// StatusCode
					if version >= 0 && version <= 999 {
						val, err := protocol.ReadInt8(r)
						if err != nil {
							return err
						}
						m.Status[i].StatusCode = val
					}
					// StatusDetail
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactString(r)
							if err != nil {
								return err
							}
							m.Status[i].StatusDetail = val
						} else {
							val, err := protocol.ReadString(r)
							if err != nil {
								return err
							}
							m.Status[i].StatusDetail = val
						}
					}
				}
			}
		} else {
			var err error
			length, err = protocol.ReadInt32(r)
			if err != nil {
				return err
			}
			if length == -1 {
				m.Status = nil
			} else {
				m.Status = make([]Status, length)
				for i := int32(0); i < length; i++ {
					// StatusCode
					if version >= 0 && version <= 999 {
						val, err := protocol.ReadInt8(r)
						if err != nil {
							return err
						}
						m.Status[i].StatusCode = val
					}
					// StatusDetail
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactString(r)
							if err != nil {
								return err
							}
							m.Status[i].StatusDetail = val
						} else {
							val, err := protocol.ReadString(r)
							if err != nil {
								return err
							}
							m.Status[i].StatusDetail = val
						}
					}
				}
			}
		}
	}
	// ActiveTasks
	if version >= 0 && version <= 999 {
		var length int32
		if isFlexible {
			var lengthUint uint32
			lengthUint, err := protocol.ReadVaruint32(r)
			if err != nil {
				return err
			}
			if lengthUint == 0 {
				m.ActiveTasks = nil
			} else {
				if lengthUint < 1 {
					return errors.New("invalid compact array length")
				}
				length = int32(lengthUint - 1)
				m.ActiveTasks = make([]TaskIds, length)
				for i := int32(0); i < length; i++ {
					// SubtopologyId
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactString(r)
							if err != nil {
								return err
							}
							m.ActiveTasks[i].SubtopologyId = val
						} else {
							val, err := protocol.ReadString(r)
							if err != nil {
								return err
							}
							m.ActiveTasks[i].SubtopologyId = val
						}
					}
					// Partitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.ActiveTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.ActiveTasks[i].Partitions[i] = val
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.ActiveTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.ActiveTasks[i].Partitions[i] = val
							}
						}
					}
				}
			}
		} else {
			var err error
			length, err = protocol.ReadInt32(r)
			if err != nil {
				return err
			}
			if length == -1 {
				m.ActiveTasks = nil
			} else {
				m.ActiveTasks = make([]TaskIds, length)
				for i := int32(0); i < length; i++ {
					// SubtopologyId
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactString(r)
							if err != nil {
								return err
							}
							m.ActiveTasks[i].SubtopologyId = val
						} else {
							val, err := protocol.ReadString(r)
							if err != nil {
								return err
							}
							m.ActiveTasks[i].SubtopologyId = val
						}
					}
					// Partitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.ActiveTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.ActiveTasks[i].Partitions[i] = val
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.ActiveTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.ActiveTasks[i].Partitions[i] = val
							}
						}
					}
				}
			}
		}
	}
	// StandbyTasks
	if version >= 0 && version <= 999 {
		var length int32
		if isFlexible {
			var lengthUint uint32
			lengthUint, err := protocol.ReadVaruint32(r)
			if err != nil {
				return err
			}
			if lengthUint == 0 {
				m.StandbyTasks = nil
			} else {
				if lengthUint < 1 {
					return errors.New("invalid compact array length")
				}
				length = int32(lengthUint - 1)
				m.StandbyTasks = make([]TaskIds, length)
				for i := int32(0); i < length; i++ {
					// SubtopologyId
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactString(r)
							if err != nil {
								return err
							}
							m.StandbyTasks[i].SubtopologyId = val
						} else {
							val, err := protocol.ReadString(r)
							if err != nil {
								return err
							}
							m.StandbyTasks[i].SubtopologyId = val
						}
					}
					// Partitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.StandbyTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.StandbyTasks[i].Partitions[i] = val
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.StandbyTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.StandbyTasks[i].Partitions[i] = val
							}
						}
					}
				}
			}
		} else {
			var err error
			length, err = protocol.ReadInt32(r)
			if err != nil {
				return err
			}
			if length == -1 {
				m.StandbyTasks = nil
			} else {
				m.StandbyTasks = make([]TaskIds, length)
				for i := int32(0); i < length; i++ {
					// SubtopologyId
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactString(r)
							if err != nil {
								return err
							}
							m.StandbyTasks[i].SubtopologyId = val
						} else {
							val, err := protocol.ReadString(r)
							if err != nil {
								return err
							}
							m.StandbyTasks[i].SubtopologyId = val
						}
					}
					// Partitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.StandbyTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.StandbyTasks[i].Partitions[i] = val
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.StandbyTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.StandbyTasks[i].Partitions[i] = val
							}
						}
					}
				}
			}
		}
	}
	// WarmupTasks
	if version >= 0 && version <= 999 {
		var length int32
		if isFlexible {
			var lengthUint uint32
			lengthUint, err := protocol.ReadVaruint32(r)
			if err != nil {
				return err
			}
			if lengthUint == 0 {
				m.WarmupTasks = nil
			} else {
				if lengthUint < 1 {
					return errors.New("invalid compact array length")
				}
				length = int32(lengthUint - 1)
				m.WarmupTasks = make([]TaskIds, length)
				for i := int32(0); i < length; i++ {
					// SubtopologyId
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactString(r)
							if err != nil {
								return err
							}
							m.WarmupTasks[i].SubtopologyId = val
						} else {
							val, err := protocol.ReadString(r)
							if err != nil {
								return err
							}
							m.WarmupTasks[i].SubtopologyId = val
						}
					}
					// Partitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.WarmupTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.WarmupTasks[i].Partitions[i] = val
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.WarmupTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.WarmupTasks[i].Partitions[i] = val
							}
						}
					}
				}
			}
		} else {
			var err error
			length, err = protocol.ReadInt32(r)
			if err != nil {
				return err
			}
			if length == -1 {
				m.WarmupTasks = nil
			} else {
				m.WarmupTasks = make([]TaskIds, length)
				for i := int32(0); i < length; i++ {
					// SubtopologyId
					if version >= 0 && version <= 999 {
						if isFlexible {
							val, err := protocol.ReadCompactString(r)
							if err != nil {
								return err
							}
							m.WarmupTasks[i].SubtopologyId = val
						} else {
							val, err := protocol.ReadString(r)
							if err != nil {
								return err
							}
							m.WarmupTasks[i].SubtopologyId = val
						}
					}
					// Partitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.WarmupTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.WarmupTasks[i].Partitions[i] = val
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.WarmupTasks[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.WarmupTasks[i].Partitions[i] = val
							}
						}
					}
				}
			}
		}
	}
	// EndpointInformationEpoch
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.EndpointInformationEpoch = val
	}
	// PartitionsByUserEndpoint
	if version >= 0 && version <= 999 {
		var length int32
		if isFlexible {
			var lengthUint uint32
			lengthUint, err := protocol.ReadVaruint32(r)
			if err != nil {
				return err
			}
			if lengthUint == 0 {
				m.PartitionsByUserEndpoint = nil
			} else {
				if lengthUint < 1 {
					return errors.New("invalid compact array length")
				}
				length = int32(lengthUint - 1)
				m.PartitionsByUserEndpoint = make([]StreamsGroupHeartbeatResponseEndpointToPartitions, length)
				for i := int32(0); i < length; i++ {
					// UserEndpoint
					if version >= 0 && version <= 999 {
					}
					// ActivePartitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.PartitionsByUserEndpoint[i].ActivePartitions = make([]TopicPartition, length)
							for i := int32(0); i < length; i++ {
								// Topic
								if version >= 0 && version <= 999 {
									if isFlexible {
										val, err := protocol.ReadCompactString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic = val
									} else {
										val, err := protocol.ReadString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic = val
									}
								}
								// Partitions
								if version >= 0 && version <= 999 {
									var length int32
									if isFlexible {
										var lengthUint uint32
										lengthUint, err := protocol.ReadVaruint32(r)
										if err != nil {
											return err
										}
										if lengthUint < 1 {
											return errors.New("invalid compact array length")
										}
										length = int32(lengthUint - 1)
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i] = val
										}
									} else {
										var err error
										length, err = protocol.ReadInt32(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i] = val
										}
									}
								}
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.PartitionsByUserEndpoint[i].ActivePartitions = make([]TopicPartition, length)
							for i := int32(0); i < length; i++ {
								// Topic
								if version >= 0 && version <= 999 {
									if isFlexible {
										val, err := protocol.ReadCompactString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic = val
									} else {
										val, err := protocol.ReadString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic = val
									}
								}
								// Partitions
								if version >= 0 && version <= 999 {
									var length int32
									if isFlexible {
										var lengthUint uint32
										lengthUint, err := protocol.ReadVaruint32(r)
										if err != nil {
											return err
										}
										if lengthUint < 1 {
											return errors.New("invalid compact array length")
										}
										length = int32(lengthUint - 1)
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i] = val
										}
									} else {
										var err error
										length, err = protocol.ReadInt32(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i] = val
										}
									}
								}
							}
						}
					}
					// StandbyPartitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.PartitionsByUserEndpoint[i].StandbyPartitions = make([]TopicPartition, length)
							for i := int32(0); i < length; i++ {
								// Topic
								if version >= 0 && version <= 999 {
									if isFlexible {
										val, err := protocol.ReadCompactString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic = val
									} else {
										val, err := protocol.ReadString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic = val
									}
								}
								// Partitions
								if version >= 0 && version <= 999 {
									var length int32
									if isFlexible {
										var lengthUint uint32
										lengthUint, err := protocol.ReadVaruint32(r)
										if err != nil {
											return err
										}
										if lengthUint < 1 {
											return errors.New("invalid compact array length")
										}
										length = int32(lengthUint - 1)
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i] = val
										}
									} else {
										var err error
										length, err = protocol.ReadInt32(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i] = val
										}
									}
								}
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.PartitionsByUserEndpoint[i].StandbyPartitions = make([]TopicPartition, length)
							for i := int32(0); i < length; i++ {
								// Topic
								if version >= 0 && version <= 999 {
									if isFlexible {
										val, err := protocol.ReadCompactString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic = val
									} else {
										val, err := protocol.ReadString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic = val
									}
								}
								// Partitions
								if version >= 0 && version <= 999 {
									var length int32
									if isFlexible {
										var lengthUint uint32
										lengthUint, err := protocol.ReadVaruint32(r)
										if err != nil {
											return err
										}
										if lengthUint < 1 {
											return errors.New("invalid compact array length")
										}
										length = int32(lengthUint - 1)
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i] = val
										}
									} else {
										var err error
										length, err = protocol.ReadInt32(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i] = val
										}
									}
								}
							}
						}
					}
				}
			}
		} else {
			var err error
			length, err = protocol.ReadInt32(r)
			if err != nil {
				return err
			}
			if length == -1 {
				m.PartitionsByUserEndpoint = nil
			} else {
				m.PartitionsByUserEndpoint = make([]StreamsGroupHeartbeatResponseEndpointToPartitions, length)
				for i := int32(0); i < length; i++ {
					// UserEndpoint
					if version >= 0 && version <= 999 {
					}
					// ActivePartitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.PartitionsByUserEndpoint[i].ActivePartitions = make([]TopicPartition, length)
							for i := int32(0); i < length; i++ {
								// Topic
								if version >= 0 && version <= 999 {
									if isFlexible {
										val, err := protocol.ReadCompactString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic = val
									} else {
										val, err := protocol.ReadString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic = val
									}
								}
								// Partitions
								if version >= 0 && version <= 999 {
									var length int32
									if isFlexible {
										var lengthUint uint32
										lengthUint, err := protocol.ReadVaruint32(r)
										if err != nil {
											return err
										}
										if lengthUint < 1 {
											return errors.New("invalid compact array length")
										}
										length = int32(lengthUint - 1)
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i] = val
										}
									} else {
										var err error
										length, err = protocol.ReadInt32(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i] = val
										}
									}
								}
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.PartitionsByUserEndpoint[i].ActivePartitions = make([]TopicPartition, length)
							for i := int32(0); i < length; i++ {
								// Topic
								if version >= 0 && version <= 999 {
									if isFlexible {
										val, err := protocol.ReadCompactString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic = val
									} else {
										val, err := protocol.ReadString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Topic = val
									}
								}
								// Partitions
								if version >= 0 && version <= 999 {
									var length int32
									if isFlexible {
										var lengthUint uint32
										lengthUint, err := protocol.ReadVaruint32(r)
										if err != nil {
											return err
										}
										if lengthUint < 1 {
											return errors.New("invalid compact array length")
										}
										length = int32(lengthUint - 1)
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i] = val
										}
									} else {
										var err error
										length, err = protocol.ReadInt32(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].ActivePartitions[i].Partitions[i] = val
										}
									}
								}
							}
						}
					}
					// StandbyPartitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.PartitionsByUserEndpoint[i].StandbyPartitions = make([]TopicPartition, length)
							for i := int32(0); i < length; i++ {
								// Topic
								if version >= 0 && version <= 999 {
									if isFlexible {
										val, err := protocol.ReadCompactString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic = val
									} else {
										val, err := protocol.ReadString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic = val
									}
								}
								// Partitions
								if version >= 0 && version <= 999 {
									var length int32
									if isFlexible {
										var lengthUint uint32
										lengthUint, err := protocol.ReadVaruint32(r)
										if err != nil {
											return err
										}
										if lengthUint < 1 {
											return errors.New("invalid compact array length")
										}
										length = int32(lengthUint - 1)
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i] = val
										}
									} else {
										var err error
										length, err = protocol.ReadInt32(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i] = val
										}
									}
								}
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.PartitionsByUserEndpoint[i].StandbyPartitions = make([]TopicPartition, length)
							for i := int32(0); i < length; i++ {
								// Topic
								if version >= 0 && version <= 999 {
									if isFlexible {
										val, err := protocol.ReadCompactString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic = val
									} else {
										val, err := protocol.ReadString(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Topic = val
									}
								}
								// Partitions
								if version >= 0 && version <= 999 {
									var length int32
									if isFlexible {
										var lengthUint uint32
										lengthUint, err := protocol.ReadVaruint32(r)
										if err != nil {
											return err
										}
										if lengthUint < 1 {
											return errors.New("invalid compact array length")
										}
										length = int32(lengthUint - 1)
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i] = val
										}
									} else {
										var err error
										length, err = protocol.ReadInt32(r)
										if err != nil {
											return err
										}
										m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions = make([]int32, length)
										for i := int32(0); i < length; i++ {
											val, err := protocol.ReadInt32(r)
											if err != nil {
												return err
											}
											m.PartitionsByUserEndpoint[i].StandbyPartitions[i].Partitions[i] = val
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	// Read tagged fields if flexible
	if isFlexible {
		if err := m.readTaggedFields(r, version); err != nil {
			return err
		}
	}
	return nil
}

// StreamsGroupHeartbeatResponseEndpointToPartitions represents Global assignment information used for IQ. Null if unchanged since last heartbeat..
type StreamsGroupHeartbeatResponseEndpointToPartitions struct {
	// User-defined endpoint to connect to the node
	UserEndpoint Endpoint `json:"userendpoint" versions:"0-999"`
	// All topic partitions materialized by active tasks on the node
	ActivePartitions []TopicPartition `json:"activepartitions" versions:"0-999"`
	// All topic partitions materialized by standby tasks on the node
	StandbyPartitions []TopicPartition `json:"standbypartitions" versions:"0-999"`
}

// writeTaggedFields writes tagged fields for StreamsGroupHeartbeatResponse.
func (m *StreamsGroupHeartbeatResponse) writeTaggedFields(w io.Writer, version int16) error {
	var taggedFieldsCount int
	var taggedFieldsBuf bytes.Buffer

	// Write tagged fields count
	if err := protocol.WriteVaruint32(w, uint32(taggedFieldsCount)); err != nil {
		return err
	}

	// Write tagged fields data
	if taggedFieldsCount > 0 {
		if _, err := w.Write(taggedFieldsBuf.Bytes()); err != nil {
			return err
		}
	}

	return nil
}

// readTaggedFields reads tagged fields for StreamsGroupHeartbeatResponse.
func (m *StreamsGroupHeartbeatResponse) readTaggedFields(r io.Reader, version int16) error {
	// Read tagged fields count
	count, err := protocol.ReadVaruint32(r)
	if err != nil {
		return err
	}

	if count == 0 {
		return nil
	}

	// Read tagged fields
	for i := uint32(0); i < count; i++ {
		tag, err := protocol.ReadVaruint32(r)
		if err != nil {
			return err
		}

		switch tag {
		default:
			// Unknown tag, skip it
			// Read and discard the field data
			// For now, we'll need to know the type to skip properly
			// This is a simplified implementation
		}
	}

	return nil
}
