package sharegroupheartbeat

import (
	"bytes"
	"fmt"
	"github.com/scholzj/go-kafka-protocol/protocol"
	"io"
)

type ShareGroupHeartbeatRequest struct {
	ApiVersion           int16
	GroupId              *string   // The group identifier. (versions: 0+)
	MemberId             *string   // The member id generated by the consumer. The member id must be kept during the entire lifetime of the consumer process. (versions: 0+)
	MemberEpoch          int32     // The current member epoch; 0 to join the group; -1 to leave the group. (versions: 0+)
	RackId               *string   // null if not provided or if it didn't change since the last heartbeat; the rack ID of consumer otherwise. (versions: 0+, nullable: 0+)
	SubscribedTopicNames *[]string // null if it didn't change since the last heartbeat; the subscribed topic names otherwise. (versions: 0+, nullable: 0+)
	rawTaggedFields      *[]protocol.TaggedField
}

func isRequestFlexible(apiVersion int16) bool {
	return apiVersion >= 0
}

func (req *ShareGroupHeartbeatRequest) Write(w io.Writer) error {
	// GroupId (versions: 0+)
	if req.GroupId == nil {
		return fmt.Errorf("ShareGroupHeartbeatRequest.GroupId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *req.GroupId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *req.GroupId); err != nil {
			return err
		}
	}

	// MemberId (versions: 0+)
	if req.MemberId == nil {
		return fmt.Errorf("ShareGroupHeartbeatRequest.MemberId must not be nil in version %d", req.ApiVersion)
	}
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteCompactString(w, *req.MemberId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteString(w, *req.MemberId); err != nil {
			return err
		}
	}

	// MemberEpoch (versions: 0+)
	if err := protocol.WriteInt32(w, req.MemberEpoch); err != nil {
		return err
	}

	// RackId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, req.RackId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, req.RackId); err != nil {
			return err
		}
	}

	// SubscribedTopicNames (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteCompactString, req.SubscribedTopicNames); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableArray(w, protocol.WriteString, req.SubscribedTopicNames); err != nil {
			return err
		}
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if req.rawTaggedFields != nil {
			rawTaggedFields = *req.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

// TODO: pass version and bytes only
func (req *ShareGroupHeartbeatRequest) Read(request *protocol.Request) error {
	if request == nil || request.Body == nil {
		return fmt.Errorf("ShareGroupHeartbeatRequest.Read: request or its body is nil")
	}

	r := bytes.NewBuffer(request.Body.Bytes())
	req.ApiVersion = request.ApiVersion

	// GroupId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		groupid, err := protocol.ReadCompactString(r)
		if err != nil {
			return err
		}
		req.GroupId = &groupid
	} else {
		groupid, err := protocol.ReadString(r)
		if err != nil {
			return err
		}
		req.GroupId = &groupid
	}

	// MemberId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		memberid, err := protocol.ReadCompactString(r)
		if err != nil {
			return err
		}
		req.MemberId = &memberid
	} else {
		memberid, err := protocol.ReadString(r)
		if err != nil {
			return err
		}
		req.MemberId = &memberid
	}

	// MemberEpoch (versions: 0+)
	memberepoch, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	req.MemberEpoch = memberepoch

	// RackId (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		rackid, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		req.RackId = rackid
	} else {
		rackid, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		req.RackId = rackid
	}

	// SubscribedTopicNames (versions: 0+)
	if isRequestFlexible(req.ApiVersion) {
		subscribedtopicnames, err := protocol.ReadNullableCompactArray(r, protocol.ReadCompactString)
		if err != nil {
			return err
		}
		req.SubscribedTopicNames = subscribedtopicnames
	} else {
		subscribedtopicnames, err := protocol.ReadNullableArray(r, protocol.ReadString)
		if err != nil {
			return err
		}
		req.SubscribedTopicNames = subscribedtopicnames
	}

	// Tagged fields
	if isRequestFlexible(req.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return err
		}
		req.rawTaggedFields = &rawTaggedFields
	}

	return nil
}

//goland:noinspection GoUnhandledErrorResult
func (req *ShareGroupHeartbeatRequest) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "    -> ShareGroupHeartbeatRequest:\n")

	if req.GroupId != nil {
		fmt.Fprintf(w, "        GroupId: %v\n", *req.GroupId)
	} else {
		fmt.Fprintf(w, "        GroupId: nil\n")
	}

	if req.MemberId != nil {
		fmt.Fprintf(w, "        MemberId: %v\n", *req.MemberId)
	} else {
		fmt.Fprintf(w, "        MemberId: nil\n")
	}

	fmt.Fprintf(w, "        MemberEpoch: %v\n", req.MemberEpoch)

	if req.RackId != nil {
		fmt.Fprintf(w, "        RackId: %v\n", *req.RackId)
	} else {
		fmt.Fprintf(w, "        RackId: nil\n")
	}

	if req.SubscribedTopicNames != nil {
		fmt.Fprintf(w, "        SubscribedTopicNames: %v\n", *req.SubscribedTopicNames)
	} else {
		fmt.Fprintf(w, "        SubscribedTopicNames: nil\n")
	}

	return w.String()
}
