package sharegroupheartbeat

import (
	"bytes"
	"fmt"
	"github.com/google/uuid"
	"github.com/scholzj/go-kafka-protocol/protocol"
	"io"
)

type ShareGroupHeartbeatResponse struct {
	ApiVersion          int16
	ThrottleTimeMs      int32                                  // The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota. (versions: 0+)
	ErrorCode           int16                                  // The top-level error code, or 0 if there was no error. (versions: 0+)
	ErrorMessage        *string                                // The top-level error message, or null if there was no error. (versions: 0+, nullable: 0+)
	MemberId            *string                                // The member ID is generated by the consumer and provided by the consumer for all requests. (versions: 0+, nullable: 0+)
	MemberEpoch         int32                                  // The member epoch. (versions: 0+)
	HeartbeatIntervalMs int32                                  // The heartbeat interval in milliseconds. (versions: 0+)
	Assignment          *ShareGroupHeartbeatResponseAssignment // null if not provided; the assignment otherwise. (versions: 0+, nullable: 0+)
	rawTaggedFields     *[]protocol.TaggedField
}

type ShareGroupHeartbeatResponseAssignment struct {
	TopicPartitions *[]ShareGroupHeartbeatResponseAssignmentTopicPartition // The partitions assigned to the member. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

type ShareGroupHeartbeatResponseAssignmentTopicPartition struct {
	TopicId         uuid.UUID // The topic ID. (versions: 0+)
	Partitions      *[]int32  // The partitions. (versions: 0+)
	rawTaggedFields *[]protocol.TaggedField
}

func isResponseFlexible(apiVersion int16) bool {
	return apiVersion >= 0
}

func (res *ShareGroupHeartbeatResponse) Write(w io.Writer) error {
	// ThrottleTimeMs (versions: 0+)
	if err := protocol.WriteInt32(w, res.ThrottleTimeMs); err != nil {
		return err
	}

	// ErrorCode (versions: 0+)
	if err := protocol.WriteInt16(w, res.ErrorCode); err != nil {
		return err
	}

	// ErrorMessage (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, res.ErrorMessage); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, res.ErrorMessage); err != nil {
			return err
		}
	}

	// MemberId (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactString(w, res.MemberId); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteNullableString(w, res.MemberId); err != nil {
			return err
		}
	}

	// MemberEpoch (versions: 0+)
	if err := protocol.WriteInt32(w, res.MemberEpoch); err != nil {
		return err
	}

	// HeartbeatIntervalMs (versions: 0+)
	if err := protocol.WriteInt32(w, res.HeartbeatIntervalMs); err != nil {
		return err
	}

	// Assignment (versions: 0+)
	if err := res.assignmentEncoder(w, *res.Assignment); err != nil {
		return err
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if res.rawTaggedFields != nil {
			rawTaggedFields = *res.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

// TODO: pass version and bytes only
func (res *ShareGroupHeartbeatResponse) Read(response *protocol.Response) error {
	if response == nil || response.Body == nil {
		return fmt.Errorf("ShareGroupHeartbeatResponse.Read: response or its body is nil")
	}

	r := bytes.NewBuffer(response.Body.Bytes())
	res.ApiVersion = response.ApiVersion

	// ThrottleTimeMs (versions: 0+)
	throttletimems, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.ThrottleTimeMs = throttletimems

	// ErrorCode (versions: 0+)
	errorcode, err := protocol.ReadInt16(r)
	if err != nil {
		return err
	}
	res.ErrorCode = errorcode

	// ErrorMessage (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		errormessage, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		res.ErrorMessage = errormessage
	} else {
		errormessage, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		res.ErrorMessage = errormessage
	}

	// MemberId (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		memberid, err := protocol.ReadNullableCompactString(r)
		if err != nil {
			return err
		}
		res.MemberId = memberid
	} else {
		memberid, err := protocol.ReadNullableString(r)
		if err != nil {
			return err
		}
		res.MemberId = memberid
	}

	// MemberEpoch (versions: 0+)
	memberepoch, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.MemberEpoch = memberepoch

	// HeartbeatIntervalMs (versions: 0+)
	heartbeatintervalms, err := protocol.ReadInt32(r)
	if err != nil {
		return err
	}
	res.HeartbeatIntervalMs = heartbeatintervalms

	// Assignment (versions: 0+)
	assignment, err := res.assignmentDecoder(r)
	if err != nil {
		return err
	}
	res.Assignment = &assignment

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return err
		}
		res.rawTaggedFields = &rawTaggedFields
	}

	return nil
}

func (res *ShareGroupHeartbeatResponse) assignmentEncoder(w io.Writer, value ShareGroupHeartbeatResponseAssignment) error {
	// TopicPartitions (versions: 0+)
	if value.TopicPartitions == nil {
		return fmt.Errorf("ShareGroupHeartbeatResponseAssignment.TopicPartitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, res.topicPartitionsEncoder, value.TopicPartitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, res.topicPartitionsEncoder, *value.TopicPartitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *ShareGroupHeartbeatResponse) assignmentDecoder(r io.Reader) (ShareGroupHeartbeatResponseAssignment, error) {
	sharegroupheartbeatresponseassignment := ShareGroupHeartbeatResponseAssignment{}

	// TopicPartitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		topicpartitions, err := protocol.ReadNullableCompactArray(r, res.topicPartitionsDecoder)
		if err != nil {
			return sharegroupheartbeatresponseassignment, err
		}
		sharegroupheartbeatresponseassignment.TopicPartitions = topicpartitions
	} else {
		topicpartitions, err := protocol.ReadArray(r, res.topicPartitionsDecoder)
		if err != nil {
			return sharegroupheartbeatresponseassignment, err
		}
		sharegroupheartbeatresponseassignment.TopicPartitions = &topicpartitions
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return sharegroupheartbeatresponseassignment, err
		}
		sharegroupheartbeatresponseassignment.rawTaggedFields = &rawTaggedFields
	}

	return sharegroupheartbeatresponseassignment, nil
}

func (res *ShareGroupHeartbeatResponse) topicPartitionsEncoder(w io.Writer, value ShareGroupHeartbeatResponseAssignmentTopicPartition) error {
	// TopicId (versions: 0+)
	if err := protocol.WriteUUID(w, value.TopicId); err != nil {
		return err
	}

	// Partitions (versions: 0+)
	if value.Partitions == nil {
		return fmt.Errorf("ShareGroupHeartbeatResponseAssignmentTopicPartition.Partitions must not be nil in version %d", res.ApiVersion)
	}
	if isResponseFlexible(res.ApiVersion) {
		if err := protocol.WriteNullableCompactArray(w, protocol.WriteInt32, value.Partitions); err != nil {
			return err
		}
	} else {
		if err := protocol.WriteArray(w, protocol.WriteInt32, *value.Partitions); err != nil {
			return err
		}
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields := []protocol.TaggedField{}
		if value.rawTaggedFields != nil {
			rawTaggedFields = *value.rawTaggedFields
		}
		if err := protocol.WriteRawTaggedFields(w, rawTaggedFields); err != nil {
			return err
		}
	}

	return nil
}

func (res *ShareGroupHeartbeatResponse) topicPartitionsDecoder(r io.Reader) (ShareGroupHeartbeatResponseAssignmentTopicPartition, error) {
	sharegroupheartbeatresponseassignmenttopicpartition := ShareGroupHeartbeatResponseAssignmentTopicPartition{}

	// TopicId (versions: 0+)
	topicid, err := protocol.ReadUUID(r)
	if err != nil {
		return sharegroupheartbeatresponseassignmenttopicpartition, err
	}
	sharegroupheartbeatresponseassignmenttopicpartition.TopicId = topicid

	// Partitions (versions: 0+)
	if isResponseFlexible(res.ApiVersion) {
		partitions, err := protocol.ReadNullableCompactArray(r, protocol.ReadInt32)
		if err != nil {
			return sharegroupheartbeatresponseassignmenttopicpartition, err
		}
		sharegroupheartbeatresponseassignmenttopicpartition.Partitions = partitions
	} else {
		partitions, err := protocol.ReadArray(r, protocol.ReadInt32)
		if err != nil {
			return sharegroupheartbeatresponseassignmenttopicpartition, err
		}
		sharegroupheartbeatresponseassignmenttopicpartition.Partitions = &partitions
	}

	// Tagged fields
	if isResponseFlexible(res.ApiVersion) {
		rawTaggedFields, err := protocol.ReadRawTaggedFields(r)
		if err != nil {
			return sharegroupheartbeatresponseassignmenttopicpartition, err
		}
		sharegroupheartbeatresponseassignmenttopicpartition.rawTaggedFields = &rawTaggedFields
	}

	return sharegroupheartbeatresponseassignmenttopicpartition, nil
}

//goland:noinspection GoUnhandledErrorResult
func (res *ShareGroupHeartbeatResponse) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "    <- ShareGroupHeartbeatResponse:\n")
	fmt.Fprintf(w, "        ThrottleTimeMs: %v\n", res.ThrottleTimeMs)
	fmt.Fprintf(w, "        ErrorCode: %v\n", res.ErrorCode)

	if res.ErrorMessage != nil {
		fmt.Fprintf(w, "        ErrorMessage: %v\n", *res.ErrorMessage)
	} else {
		fmt.Fprintf(w, "        ErrorMessage: nil\n")
	}

	if res.MemberId != nil {
		fmt.Fprintf(w, "        MemberId: %v\n", *res.MemberId)
	} else {
		fmt.Fprintf(w, "        MemberId: nil\n")
	}

	fmt.Fprintf(w, "        MemberEpoch: %v\n", res.MemberEpoch)
	fmt.Fprintf(w, "        HeartbeatIntervalMs: %v\n", res.HeartbeatIntervalMs)

	fmt.Fprintf(w, "        Assignment:\n")
	if res.Assignment != nil {
		fmt.Fprintf(w, "%s", res.Assignment.PrettyPrint())
	} else {
		fmt.Fprintf(w, "            nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *ShareGroupHeartbeatResponseAssignment) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	if value.TopicPartitions != nil {
		fmt.Fprintf(w, "            TopicPartitions:\n")
		for _, topicpartitions := range *value.TopicPartitions {
			fmt.Fprintf(w, "%s", topicpartitions.PrettyPrint())
			fmt.Fprintf(w, "                ----------------\n")
		}
	} else {
		fmt.Fprintf(w, "            TopicPartitions: nil\n")
	}

	return w.String()
}

//goland:noinspection GoUnhandledErrorResult
func (value *ShareGroupHeartbeatResponseAssignmentTopicPartition) PrettyPrint() string {
	w := bytes.NewBuffer([]byte{})

	fmt.Fprintf(w, "                TopicId: %v\n", value.TopicId)

	if value.Partitions != nil {
		fmt.Fprintf(w, "                Partitions: %v\n", *value.Partitions)
	} else {
		fmt.Fprintf(w, "                Partitions: nil\n")
	}

	return w.String()
}
