package sharegroupheartbeat

import (
	"bytes"
	"errors"
	"io"

	"github.com/google/uuid"
	"github.com/scholzj/go-kafka-protocol/protocol"
)

const (
	ShareGroupHeartbeatResponseApiKey        = 76
	ShareGroupHeartbeatResponseHeaderVersion = 1
)

// ShareGroupHeartbeatResponse represents a response message.
type ShareGroupHeartbeatResponse struct {
	// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
	ThrottleTimeMs int32 `json:"throttletimems" versions:"0-999"`
	// The top-level error code, or 0 if there was no error.
	ErrorCode int16 `json:"errorcode" versions:"0-999"`
	// The top-level error message, or null if there was no error.
	ErrorMessage *string `json:"errormessage" versions:"0-999"`
	// The member ID is generated by the consumer and provided by the consumer for all requests.
	MemberId *string `json:"memberid" versions:"0-999"`
	// The member epoch.
	MemberEpoch int32 `json:"memberepoch" versions:"0-999"`
	// The heartbeat interval in milliseconds.
	HeartbeatIntervalMs int32 `json:"heartbeatintervalms" versions:"0-999"`
	// null if not provided; the assignment otherwise.
	Assignment ShareGroupHeartbeatResponseAssignment `json:"assignment" versions:"0-999"`
}

// Encode encodes a ShareGroupHeartbeatResponse to a byte slice for the given version.
func (m *ShareGroupHeartbeatResponse) Encode(version int16) ([]byte, error) {
	var buf bytes.Buffer
	if err := m.Write(&buf, version); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Decode decodes a ShareGroupHeartbeatResponse from a byte slice for the given version.
func (m *ShareGroupHeartbeatResponse) Decode(data []byte, version int16) error {
	r := bytes.NewReader(data)
	return m.Read(r, version)
}

// Write writes a ShareGroupHeartbeatResponse to an io.Writer for the given version.
func (m *ShareGroupHeartbeatResponse) Write(w io.Writer, version int16) error {
	if version < 1 || version > 1 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// ThrottleTimeMs
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.ThrottleTimeMs); err != nil {
			return err
		}
	}
	// ErrorCode
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt16(w, m.ErrorCode); err != nil {
			return err
		}
	}
	// ErrorMessage
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.ErrorMessage); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.ErrorMessage); err != nil {
				return err
			}
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.MemberId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.MemberId); err != nil {
				return err
			}
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.MemberEpoch); err != nil {
			return err
		}
	}
	// HeartbeatIntervalMs
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.HeartbeatIntervalMs); err != nil {
			return err
		}
	}
	// Assignment
	if version >= 0 && version <= 999 {
		// TopicPartitions
		if version >= 0 && version <= 999 {
			if isFlexible {
				length := uint32(len(m.Assignment.TopicPartitions) + 1)
				if err := protocol.WriteVaruint32(w, length); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, int32(len(m.Assignment.TopicPartitions))); err != nil {
					return err
				}
			}
			for i := range m.Assignment.TopicPartitions {
				// TopicId
				if version >= 0 && version <= 999 {
					if err := protocol.WriteUUID(w, m.Assignment.TopicPartitions[i].TopicId); err != nil {
						return err
					}
				}
				// Partitions
				if version >= 0 && version <= 999 {
					if isFlexible {
						length := uint32(len(m.Assignment.TopicPartitions[i].Partitions) + 1)
						if err := protocol.WriteVaruint32(w, length); err != nil {
							return err
						}
					} else {
						if err := protocol.WriteInt32(w, int32(len(m.Assignment.TopicPartitions[i].Partitions))); err != nil {
							return err
						}
					}
					for i := range m.Assignment.TopicPartitions[i].Partitions {
						if err := protocol.WriteInt32(w, m.Assignment.TopicPartitions[i].Partitions[i]); err != nil {
							return err
						}
						_ = i
					}
				}
			}
		}
	}
	// Write tagged fields if flexible
	if isFlexible {
		if err := m.writeTaggedFields(w, version); err != nil {
			return err
		}
	}
	return nil
}

// Read reads a ShareGroupHeartbeatResponse from an io.Reader for the given version.
func (m *ShareGroupHeartbeatResponse) Read(r io.Reader, version int16) error {
	if version < 1 || version > 1 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// ThrottleTimeMs
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.ThrottleTimeMs = val
	}
	// ErrorCode
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt16(r)
		if err != nil {
			return err
		}
		m.ErrorCode = val
	}
	// ErrorMessage
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.ErrorMessage = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.ErrorMessage = val
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.MemberEpoch = val
	}
	// HeartbeatIntervalMs
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.HeartbeatIntervalMs = val
	}
	// Assignment
	if version >= 0 && version <= 999 {
		// TopicPartitions
		if version >= 0 && version <= 999 {
			var length int32
			if isFlexible {
				var lengthUint uint32
				lengthUint, err := protocol.ReadVaruint32(r)
				if err != nil {
					return err
				}
				if lengthUint < 1 {
					return errors.New("invalid compact array length")
				}
				length = int32(lengthUint - 1)
				m.Assignment.TopicPartitions = make([]TopicPartitions, length)
				for i := int32(0); i < length; i++ {
					// TopicId
					if version >= 0 && version <= 999 {
						val, err := protocol.ReadUUID(r)
						if err != nil {
							return err
						}
						m.Assignment.TopicPartitions[i].TopicId = val
					}
					// Partitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.Assignment.TopicPartitions[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.Assignment.TopicPartitions[i].Partitions[i] = val
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.Assignment.TopicPartitions[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.Assignment.TopicPartitions[i].Partitions[i] = val
							}
						}
					}
				}
			} else {
				var err error
				length, err = protocol.ReadInt32(r)
				if err != nil {
					return err
				}
				m.Assignment.TopicPartitions = make([]TopicPartitions, length)
				for i := int32(0); i < length; i++ {
					// TopicId
					if version >= 0 && version <= 999 {
						val, err := protocol.ReadUUID(r)
						if err != nil {
							return err
						}
						m.Assignment.TopicPartitions[i].TopicId = val
					}
					// Partitions
					if version >= 0 && version <= 999 {
						var length int32
						if isFlexible {
							var lengthUint uint32
							lengthUint, err := protocol.ReadVaruint32(r)
							if err != nil {
								return err
							}
							if lengthUint < 1 {
								return errors.New("invalid compact array length")
							}
							length = int32(lengthUint - 1)
							m.Assignment.TopicPartitions[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.Assignment.TopicPartitions[i].Partitions[i] = val
							}
						} else {
							var err error
							length, err = protocol.ReadInt32(r)
							if err != nil {
								return err
							}
							m.Assignment.TopicPartitions[i].Partitions = make([]int32, length)
							for i := int32(0); i < length; i++ {
								val, err := protocol.ReadInt32(r)
								if err != nil {
									return err
								}
								m.Assignment.TopicPartitions[i].Partitions[i] = val
							}
						}
					}
				}
			}
		}
	}
	// Read tagged fields if flexible
	if isFlexible {
		if err := m.readTaggedFields(r, version); err != nil {
			return err
		}
	}
	return nil
}

// ShareGroupHeartbeatResponseAssignment represents null if not provided; the assignment otherwise..
type ShareGroupHeartbeatResponseAssignment struct {
	// The partitions assigned to the member.
	TopicPartitions []TopicPartitions `json:"topicpartitions" versions:"0-999"`
}

// writeTaggedFields writes tagged fields for ShareGroupHeartbeatResponse.
func (m *ShareGroupHeartbeatResponse) writeTaggedFields(w io.Writer, version int16) error {
	var taggedFieldsCount int
	var taggedFieldsBuf bytes.Buffer

	// Write tagged fields count
	if err := protocol.WriteVaruint32(w, uint32(taggedFieldsCount)); err != nil {
		return err
	}

	// Write tagged fields data
	if taggedFieldsCount > 0 {
		if _, err := w.Write(taggedFieldsBuf.Bytes()); err != nil {
			return err
		}
	}

	return nil
}

// readTaggedFields reads tagged fields for ShareGroupHeartbeatResponse.
func (m *ShareGroupHeartbeatResponse) readTaggedFields(r io.Reader, version int16) error {
	// Read tagged fields count
	count, err := protocol.ReadVaruint32(r)
	if err != nil {
		return err
	}

	if count == 0 {
		return nil
	}

	// Read tagged fields
	for i := uint32(0); i < count; i++ {
		tag, err := protocol.ReadVaruint32(r)
		if err != nil {
			return err
		}

		switch tag {
		default:
			// Unknown tag, skip it
			// Read and discard the field data
			// For now, we'll need to know the type to skip properly
			// This is a simplified implementation
		}
	}

	return nil
}
