package sharegroupheartbeat

import (
	"bytes"
	"errors"
	"io"

	"github.com/google/uuid"
	"github.com/scholzj/go-kafka-protocol/protocol"
)

const (
	ShareGroupHeartbeatRequestApiKey        = 76
	ShareGroupHeartbeatRequestHeaderVersion = 1
)

// ShareGroupHeartbeatRequest represents a request message.
type ShareGroupHeartbeatRequest struct {
	// The group identifier.
	GroupId string `json:"groupid" versions:"0-999"`
	// The member id generated by the consumer. The member id must be kept during the entire lifetime of the consumer process.
	MemberId string `json:"memberid" versions:"0-999"`
	// The current member epoch; 0 to join the group; -1 to leave the group.
	MemberEpoch int32 `json:"memberepoch" versions:"0-999"`
	// null if not provided or if it didn't change since the last heartbeat; the rack ID of consumer otherwise.
	RackId *string `json:"rackid" versions:"0-999"`
	// null if it didn't change since the last heartbeat; the subscribed topic names otherwise.
	SubscribedTopicNames []string `json:"subscribedtopicnames" versions:"0-999"`
}

// Encode encodes a ShareGroupHeartbeatRequest to a byte slice for the given version.
func (m *ShareGroupHeartbeatRequest) Encode(version int16) ([]byte, error) {
	var buf bytes.Buffer
	if err := m.Write(&buf, version); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Decode decodes a ShareGroupHeartbeatRequest from a byte slice for the given version.
func (m *ShareGroupHeartbeatRequest) Decode(data []byte, version int16) error {
	r := bytes.NewReader(data)
	return m.Read(r, version)
}

// Write writes a ShareGroupHeartbeatRequest to an io.Writer for the given version.
func (m *ShareGroupHeartbeatRequest) Write(w io.Writer, version int16) error {
	if version < 1 || version > 1 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// GroupId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactString(w, m.GroupId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteString(w, m.GroupId); err != nil {
				return err
			}
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactString(w, m.MemberId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteString(w, m.MemberId); err != nil {
				return err
			}
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		if err := protocol.WriteInt32(w, m.MemberEpoch); err != nil {
			return err
		}
	}
	// RackId
	if version >= 0 && version <= 999 {
		if isFlexible {
			if err := protocol.WriteCompactNullableString(w, m.RackId); err != nil {
				return err
			}
		} else {
			if err := protocol.WriteNullableString(w, m.RackId); err != nil {
				return err
			}
		}
	}
	// SubscribedTopicNames
	if version >= 0 && version <= 999 {
		if m.SubscribedTopicNames == nil {
			if isFlexible {
				if err := protocol.WriteVaruint32(w, 0); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, -1); err != nil {
					return err
				}
			}
		} else {
			if isFlexible {
				length := uint32(len(m.SubscribedTopicNames) + 1)
				if err := protocol.WriteVaruint32(w, length); err != nil {
					return err
				}
			} else {
				if err := protocol.WriteInt32(w, int32(len(m.SubscribedTopicNames))); err != nil {
					return err
				}
			}
			for i := range m.SubscribedTopicNames {
				if isFlexible {
					if err := protocol.WriteCompactString(w, m.SubscribedTopicNames[i]); err != nil {
						return err
					}
				} else {
					if err := protocol.WriteString(w, m.SubscribedTopicNames[i]); err != nil {
						return err
					}
				}
				_ = i
			}
		}
	}
	// Write tagged fields if flexible
	if isFlexible {
		if err := m.writeTaggedFields(w, version); err != nil {
			return err
		}
	}
	return nil
}

// Read reads a ShareGroupHeartbeatRequest from an io.Reader for the given version.
func (m *ShareGroupHeartbeatRequest) Read(r io.Reader, version int16) error {
	if version < 1 || version > 1 {
		return errors.New("unsupported version")
	}

	isFlexible := false
	if version >= 0 {
		isFlexible = true
	}

	// GroupId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactString(r)
			if err != nil {
				return err
			}
			m.GroupId = val
		} else {
			val, err := protocol.ReadString(r)
			if err != nil {
				return err
			}
			m.GroupId = val
		}
	}
	// MemberId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		} else {
			val, err := protocol.ReadString(r)
			if err != nil {
				return err
			}
			m.MemberId = val
		}
	}
	// MemberEpoch
	if version >= 0 && version <= 999 {
		val, err := protocol.ReadInt32(r)
		if err != nil {
			return err
		}
		m.MemberEpoch = val
	}
	// RackId
	if version >= 0 && version <= 999 {
		if isFlexible {
			val, err := protocol.ReadCompactNullableString(r)
			if err != nil {
				return err
			}
			m.RackId = val
		} else {
			val, err := protocol.ReadNullableString(r)
			if err != nil {
				return err
			}
			m.RackId = val
		}
	}
	// SubscribedTopicNames
	if version >= 0 && version <= 999 {
		var length int32
		if isFlexible {
			var lengthUint uint32
			lengthUint, err := protocol.ReadVaruint32(r)
			if err != nil {
				return err
			}
			if lengthUint == 0 {
				m.SubscribedTopicNames = nil
			} else {
				if lengthUint < 1 {
					return errors.New("invalid compact array length")
				}
				length = int32(lengthUint - 1)
				m.SubscribedTopicNames = make([]string, length)
				for i := int32(0); i < length; i++ {
					if isFlexible {
						val, err := protocol.ReadCompactString(r)
						if err != nil {
							return err
						}
						m.SubscribedTopicNames[i] = val
					} else {
						val, err := protocol.ReadString(r)
						if err != nil {
							return err
						}
						m.SubscribedTopicNames[i] = val
					}
				}
			}
		} else {
			var err error
			length, err = protocol.ReadInt32(r)
			if err != nil {
				return err
			}
			if length == -1 {
				m.SubscribedTopicNames = nil
			} else {
				m.SubscribedTopicNames = make([]string, length)
				for i := int32(0); i < length; i++ {
					if isFlexible {
						val, err := protocol.ReadCompactString(r)
						if err != nil {
							return err
						}
						m.SubscribedTopicNames[i] = val
					} else {
						val, err := protocol.ReadString(r)
						if err != nil {
							return err
						}
						m.SubscribedTopicNames[i] = val
					}
				}
			}
		}
	}
	// Read tagged fields if flexible
	if isFlexible {
		if err := m.readTaggedFields(r, version); err != nil {
			return err
		}
	}
	return nil
}

// TopicPartitions represents .
type TopicPartitions struct {
	// The topic ID.
	TopicId uuid.UUID `json:"topicid" versions:"0-999"`
	// The partitions.
	Partitions []int32 `json:"partitions" versions:"0-999"`
}

// writeTaggedFields writes tagged fields for ShareGroupHeartbeatRequest.
func (m *ShareGroupHeartbeatRequest) writeTaggedFields(w io.Writer, version int16) error {
	var taggedFieldsCount int
	var taggedFieldsBuf bytes.Buffer

	// Write tagged fields count
	if err := protocol.WriteVaruint32(w, uint32(taggedFieldsCount)); err != nil {
		return err
	}

	// Write tagged fields data
	if taggedFieldsCount > 0 {
		if _, err := w.Write(taggedFieldsBuf.Bytes()); err != nil {
			return err
		}
	}

	return nil
}

// readTaggedFields reads tagged fields for ShareGroupHeartbeatRequest.
func (m *ShareGroupHeartbeatRequest) readTaggedFields(r io.Reader, version int16) error {
	// Read tagged fields count
	count, err := protocol.ReadVaruint32(r)
	if err != nil {
		return err
	}

	if count == 0 {
		return nil
	}

	// Read tagged fields
	for i := uint32(0); i < count; i++ {
		tag, err := protocol.ReadVaruint32(r)
		if err != nil {
			return err
		}

		switch tag {
		default:
			// Unknown tag, skip it
			// Read and discard the field data
			// For now, we'll need to know the type to skip properly
			// This is a simplified implementation
		}
	}

	return nil
}
